import { Item, CraftRecipe, Quest, NPC, Monster, ResourceNode, Obstacle, InteractiveObject, Platform, WorldPOI, CharacterClass, GunType } from '../types/game';
import { getInteriorRoom } from './buildings';

export const WORLD_WIDTH = 5400;
export const WORLD_HEIGHT = 4400;
export const NPC_INTERACT_RANGE = 110;
export const DAY_CYCLE_SECONDS = 720;

export const ZONES = [
  {
    id: 'forest_camp',
    name: 'Survivor Forest Campsite',
    bounds: { minX: 100, minY: 100, maxX: 1800, maxY: 1600 },
    bgTheme: 'camp',
    desc: 'Deep pine woods with expedition canvas tents, roaring campfire, supply crates, and friendly survivor NPCs.',
  },
  {
    id: 'deep_forest',
    name: 'Dense Ancient Redwood & Pine Forest',
    bounds: { minX: 100, minY: 1600, maxX: 2600, maxY: 3100 },
    bgTheme: 'forest',
    desc: 'Dense ancient woods with towering giant trees, forest stream, ranger treehouse, spirit shrine, and harvestable timber.',
  },
  {
    id: 'rocky_canyon',
    name: 'Redrock Chasm & Suspension Bridges',
    bounds: { minX: 1800, minY: 100, maxX: 5300, maxY: 1600 },
    bgTheme: 'canyon',
    desc: 'Steep multi-tiered ravines with aerial rope suspension bridges, geothermal steam geysers, and outlaw sniper nests.',
  },
  {
    id: 'welder_crag',
    name: 'High Rock Summit & Welder Arena',
    bounds: { minX: 2600, minY: 1600, maxX: 5300, maxY: 3100 },
    bgTheme: 'mountain',
    desc: 'Towering cliff plateau guarded by the brutal hammer-wielding boss "Iron Mask" Sledge!',
  },
  {
    id: 'cop_precinct',
    name: 'SWAT Metro Precinct (Left Warzone)',
    bounds: { minX: 100, minY: 3100, maxX: 2400, maxY: 4300 },
    bgTheme: 'police',
    desc: 'Heavily fortified SWAT police sector with riot barriers, tactical officers, batons, and Titan Juggernauts.',
  },
  {
    id: 'punk_territory',
    name: 'Demon Punk Alley (Right Warzone)',
    bounds: { minX: 2800, minY: 3100, maxX: 5300, maxY: 4300 },
    bgTheme: 'punk',
    desc: 'Neon-lit gang turf of Punk Demons with spiked bats, MAC-10s, Molotov cocktails, and Hellfire Jax.',
  },
  {
    id: 'warzone_frontline',
    name: 'Street Frontline (No-Mans Land)',
    bounds: { minX: 2200, minY: 3100, maxX: 3000, maxY: 4300 },
    bgTheme: 'warzone',
    desc: 'Active clash line where Cops and Punks engage in constant warfare unless provoked by the player.',
  },
  {
    id: 'horde_crucible',
    name: 'Nullspace Rack (Endless Crucible)',
    bounds: { minX: -11200, minY: -2400, maxX: -800, maxY: 6800 },
    bgTheme: 'horde',
    desc: 'A torn-open server meta-space. Endless slaughter, new horrors every 20 seconds, bosses every minute.',
  },
];

// ELEVATED PLATFORMS, BRIDGES, TREEHOUSES & CLIFF PLATEAUS
export const PLATFORMS: Platform[] = [
  // 1. Forest Ranger High Treehouse (x: 450, y: 2200, elevation: 90px)
  {
    id: 'plat_treehouse_main',
    name: "Ranger's Treehouse Platform",
    x: 450,
    y: 2150,
    width: 240,
    height: 190,
    elevationZ: 90,
    type: 'treehouse',
  },
  // Treehouse access wooden stairs/ramp (leads from ground up to 90px)
  {
    id: 'plat_treehouse_ramp',
    name: 'Treehouse Wooden Ladder Ramp',
    x: 420,
    y: 2320,
    width: 80,
    height: 90,
    elevationZ: 90,
    type: 'ramp',
    rampDirection: 'up_y',
    rampElevationStart: 0,
    rampElevationEnd: 90,
  },

  // 2. Canyon High North Plateau (x: 2200..3800, y: 120..480, elevation: 140px)
  {
    id: 'plat_canyon_north_plateau',
    name: 'North Eagle Cliff Plateau',
    x: 2280,
    y: 120,
    width: 1550,
    height: 380,
    elevationZ: 140,
    type: 'plateau',
  },
  // North Plateau West Stone Ramp (leads from low canyon ground 0 to 140px)
  {
    id: 'plat_canyon_north_ramp',
    name: 'North Cliff Stone Ramp',
    x: 2120,
    y: 260,
    width: 170,
    height: 140,
    elevationZ: 140,
    type: 'ramp',
    rampDirection: 'up_x',
    rampElevationStart: 0,
    rampElevationEnd: 140,
  },

  // 3. Canyon High South Plateau (x: 2200..3850, y: 1080..1520, elevation: 140px)
  {
    id: 'plat_canyon_south_plateau',
    name: 'South Redrock Plateau',
    x: 2280,
    y: 1080,
    width: 1600,
    height: 460,
    elevationZ: 140,
    type: 'plateau',
  },
  // South Plateau East Natural Ramp (leads from 140px down to low canyon ground)
  {
    id: 'plat_canyon_south_ramp',
    name: 'South Plateau Scree Ramp',
    x: 3850,
    y: 1140,
    width: 170,
    height: 140,
    elevationZ: 140,
    type: 'ramp',
    rampDirection: 'down_x',
    rampElevationStart: 140,
    rampElevationEnd: 0,
  },

  // 4. Aerial Suspension Rope Bridge #1 (West Chasm Span over Gorge)
  {
    id: 'plat_suspension_bridge_west',
    name: 'Skyview Suspension Bridge',
    x: 2680,
    y: 490,
    width: 130,
    height: 600,
    elevationZ: 140,
    type: 'bridge',
  },

  // 5. Aerial Suspension Rope Bridge #2 (East Chasm Span over Gorge)
  {
    id: 'plat_suspension_bridge_east',
    name: 'Eagle Ridge Suspension Bridge',
    x: 3420,
    y: 490,
    width: 130,
    height: 600,
    elevationZ: 140,
    type: 'bridge',
  },

  // 6. High Rock Summit Plateau (Welder Boss Arena)
  {
    id: 'plat_summit_arena',
    name: 'Summit Basalt Arena Plateau',
    x: 2850,
    y: 1800,
    width: 1750,
    height: 1200,
    elevationZ: 120,
    type: 'plateau',
  },
  // Summit Arena Mountain Ascent Ramp
  {
    id: 'plat_summit_ramp',
    name: 'Summit Ascent Ramp',
    x: 2650,
    y: 2280,
    width: 220,
    height: 140,
    elevationZ: 120,
    type: 'ramp',
    rampDirection: 'up_x',
    rampElevationStart: 0,
    rampElevationEnd: 120,
  },

  // City skybridges only — building interiors/roofs live in BUILDINGS (hollow volumes).
  {
    id: 'plat_metro_skybridge',
    name: 'Metro Police Skybridge',
    x: 880,
    y: 3360,
    width: 180,
    height: 75,
    elevationZ: 210,
    type: 'bridge',
  },

  // 7.3. Elevated Monorail Track & Crashed Train Car (elevation: 110px)
  {
    id: 'plat_monorail_track',
    name: 'Elevated Monorail Transit Rail',
    x: 300,
    y: 3950,
    width: 1750,
    height: 90,
    elevationZ: 110,
    type: 'bridge',
  },
  {
    id: 'plat_monorail_train',
    name: 'Derelict Metro Train Carriage',
    x: 1050,
    y: 3930,
    width: 320,
    height: 110,
    elevationZ: 110,
    type: 'scaffold',
  },
  // Monorail Fallen Steel Girder Ascent Ramp
  {
    id: 'plat_monorail_ramp',
    name: 'Fallen Girder Monorail Ramp',
    x: 280,
    y: 3930,
    width: 140,
    height: 100,
    elevationZ: 110,
    type: 'ramp',
    rampDirection: 'up_x',
    rampElevationStart: 0,
    rampElevationEnd: 110,
  },

  {
    id: 'plat_punk_pipe_bridge',
    name: 'Steam Pipe Catwalk',
    x: 3650,
    y: 3360,
    width: 200,
    height: 75,
    elevationZ: 210,
    type: 'bridge',
  },
];

// POINTS OF INTEREST (POIs) - Shrines, Geysers, Bouncy Mushrooms, Vending Machines, Hydrants, Caches
export const WORLD_POIS: WorldPOI[] = [
  // Forest: Ancient Spirit Shrine
  {
    id: 'poi_spirit_shrine',
    name: 'Ancient Wind Spirit Shrine',
    type: 'spirit_shrine',
    x: 1950,
    y: 2150,
    radius: 50,
    buffType: 'speed',
    buffValue: 0.45,
    buffDuration: 25,
    icon: '🎐',
    description: 'Ancient mossy monolith humming with swift gale energy. Grants +45% Speed!',
  },

  // Forest: Bouncy Bioluminescent Mushrooms (Launch pads)
  {
    id: 'poi_shroom_forest_1',
    name: 'Bouncy Bio-Mushroom',
    type: 'bouncy_mushroom',
    x: 820,
    y: 1900,
    radius: 36,
    icon: '🍄',
    description: 'Springy giant mushroom cap that launches characters sky-high!',
  },
  {
    id: 'poi_shroom_forest_2',
    name: 'Bouncy Bio-Mushroom',
    type: 'bouncy_mushroom',
    x: 1680,
    y: 2650,
    radius: 36,
    icon: '🍄',
  },

  // Forest: Ranger Treehouse Secret Weapon Stash
  {
    id: 'poi_treehouse_cache',
    name: "Ranger's Secret Stash",
    type: 'treehouse_cache',
    x: 530,
    y: 2220,
    elevationZ: 90,
    radius: 32,
    isLooted: false,
    lootTable: [
      { itemId: 'wpn_bandit_revolver', minQty: 1, maxQty: 1, chance: 1.0 },
      { itemId: 'mat_lumite_crystal', minQty: 4, maxQty: 8, chance: 1.0 },
      { itemId: 'pot_hp_large', minQty: 3, maxQty: 5, chance: 1.0 },
    ],
    icon: '📦',
    description: 'Locked tactical crate left behind on the high treehouse platform.',
  },

  // Canyon: Geothermal High-Pressure Steam Geysers
  {
    id: 'poi_geyser_canyon_1',
    name: 'Volcanic Steam Geyser',
    type: 'steam_geyser',
    x: 2745,
    y: 790,
    radius: 42,
    icon: '💨',
    description: 'Surging geyser blowing pressurized steam straight up to the rope bridge!',
  },
  {
    id: 'poi_geyser_canyon_2',
    name: 'Volcanic Steam Geyser',
    type: 'steam_geyser',
    x: 3485,
    y: 790,
    radius: 42,
    icon: '💨',
    description: 'High-power geyser launching characters up onto the East suspension bridge!',
  },

  // Canyon: Derelict Ore Minecart in Low Gorge
  {
    id: 'poi_minecart_gorge',
    name: 'Derelict Gold Minecart',
    type: 'minecart_cart',
    x: 3080,
    y: 830,
    radius: 38,
    isLooted: false,
    lootTable: [
      { itemId: 'mat_iron_chunk', minQty: 8, maxQty: 14, chance: 1.0 },
      { itemId: 'mat_refined_steel', minQty: 3, maxQty: 6, chance: 0.9 },
      { itemId: 'wpn_shotgun', minQty: 1, maxQty: 1, chance: 0.7 },
    ],
    icon: '⛏️',
    description: 'Rusty mining cart packed with heavy ores and explosives.',
  },

  // Canyon: High Eagle Cliff Weapon Crate
  {
    id: 'poi_eagle_cliff_chest',
    name: 'Eagle Cliff Sniper Cache',
    type: 'treasure_chest',
    x: 3620,
    y: 260,
    elevationZ: 140,
    radius: 32,
    isLooted: false,
    lootTable: [
      { itemId: 'wpn_cheytac', minQty: 1, maxQty: 1, chance: 0.75 },
      { itemId: 'att_muzzle_compensator', minQty: 1, maxQty: 1, chance: 1.0 },
      { itemId: 'att_optic_holo', minQty: 1, maxQty: 1, chance: 1.0 },
    ],
    icon: '🎁',
    description: 'Mil-spec weapon supply drop sitting atop the highest canyon ledge.',
  },

  // ==========================================
  // CITY SECTOR: VENDING MACHINES, HYDRANTS & ROOFTOP VAULTS
  // ==========================================
  // Metro Precinct Interactive Cyber Vending Machine
  {
    id: 'poi_vending_metro',
    name: 'Metro Cyber-Cola & Stims Dispenser',
    type: 'vending_machine',
    x: 920,
    y: 3620,
    radius: 36,
    icon: '🥤',
    description: 'Hit or interact to dispense chilled Energy Sodas and 9mm Ammo!',
    lootTable: [
      { itemId: 'pot_hp_large', minQty: 1, maxQty: 2, chance: 1.0 },
      { itemId: 'mat_refined_steel', minQty: 2, maxQty: 4, chance: 0.8 },
    ],
  },
  // Punk Alley Demon-Energy Vending Machine
  {
    id: 'poi_vending_punk',
    name: 'Hellfire Energy Machine',
    type: 'vending_machine',
    x: 3250,
    y: 3650,
    radius: 36,
    icon: '⚡',
    description: 'Battered gang vending machine spitting out fiery stimpacks!',
    lootTable: [
      { itemId: 'pot_hp_large', minQty: 1, maxQty: 2, chance: 1.0 },
      { itemId: 'mat_lumite_crystal', minQty: 2, maxQty: 3, chance: 0.75 },
    ],
  },

  // High-Pressure Street Fire Hydrants (Geysers that launch player onto roofs!)
  {
    id: 'poi_hydrant_metro_1',
    name: 'Pressurized Fire Hydrant',
    type: 'fire_hydrant',
    x: 1010,
    y: 3590,
    radius: 36,
    icon: '🚰',
    description: 'Burst fire hydrant blasting a roaring water column straight onto the Noodle roof!',
  },
  {
    id: 'poi_hydrant_metro_2',
    name: 'Pressurized Fire Hydrant',
    type: 'fire_hydrant',
    x: 1750,
    y: 3590,
    radius: 36,
    icon: '🚰',
  },
  {
    id: 'poi_hydrant_punk_1',
    name: 'Pressurized Fire Hydrant',
    type: 'fire_hydrant',
    x: 3550,
    y: 3590,
    radius: 36,
    icon: '🚰',
  },

  // Police HQ Skyscraper Rooftop Armory Locker (elevation: 200px)
  {
    id: 'poi_police_hq_chest',
    name: 'SWAT Rooftop Armory Locker',
    type: 'treasure_chest',
    x: 580,
    y: 3340,
    elevationZ: 210,
    radius: 32,
    isLooted: false,
    lootTable: [
      { itemId: 'wpn_mac10', minQty: 1, maxQty: 1, chance: 1.0 },
      { itemId: 'att_mag_extended', minQty: 1, maxQty: 1, chance: 1.0 },
      { itemId: 'pot_hp_large', minQty: 3, maxQty: 5, chance: 1.0 },
    ],
    icon: '🛡️',
    description: 'Locked heavy police supply case atop the HQ Helipad.',
  },

  // Punk Tower Rooftop Hellfire Boss Vault (elevation: 190px)
  {
    id: 'poi_punk_tower_chest',
    name: 'Hellfire Boss Rooftop Vault',
    type: 'treasure_chest',
    x: 4050,
    y: 3340,
    elevationZ: 210,
    radius: 32,
    isLooted: false,
    lootTable: [
      { itemId: 'wpn_ak47', minQty: 1, maxQty: 1, chance: 0.85 },
      { itemId: 'att_under_laser', minQty: 1, maxQty: 1, chance: 1.0 },
      { itemId: 'mat_lumite_crystal', minQty: 5, maxQty: 10, chance: 1.0 },
    ],
    icon: '👑',
    description: 'Anarchy syndicate master safe locked on the highest tower roof.',
  },

  // ==========================================
  // HOSTINGOVAYA DATA CENTER POIs
  // ==========================================
  {
    id: 'poi_hostingovaya_checkpoint',
    name: 'HOSTINGOVAYA Security Checkpoint',
    type: 'spirit_shrine',
    x: 1880,
    y: 3580,
    radius: 50,
    icon: '🚨',
    description: 'Turnstiles & laser scanners. Trespassing or smashing servers triggers total security lockdown!',
  },
  {
    id: 'poi_hostingovaya_quantum_vault',
    name: 'Quantum Core Master Backup Safe',
    type: 'treasure_chest',
    x: 1880,
    y: 3280,
    elevationZ: 210,
    radius: 35,
    isLooted: false,
    lootTable: [
      { itemId: 'wpn_cheytac', minQty: 1, maxQty: 1, chance: 0.9 },
      { itemId: 'mat_refined_steel', minQty: 8, maxQty: 16, chance: 1.0 },
      { itemId: 'mat_lumite_crystal', minQty: 6, maxQty: 12, chance: 1.0 },
      { itemId: 'pot_hp_large', minQty: 4, maxQty: 8, chance: 1.0 },
    ],
    icon: '💻',
    description: 'Encrypted master vault containing quantum supercomputing chips and sniper blueprints.',
  },
];

// SOLID & VAULTABLE OBSTACLES (Walkable vs Non-Walkable vs Vaultable Planes)
export const OBSTACLES: Obstacle[] = [
  // Forest Campsite Large Tents (Solid cloth & frame structures)
  { id: 'tent_main_hq', x: 580, y: 480, width: 140, height: 110, type: 'tent', obstacleHeight: 120, canVault: false },
  { id: 'tent_armory', x: 860, y: 480, width: 130, height: 100, type: 'tent', obstacleHeight: 110, canVault: false },
  { id: 'tent_kitchen', x: 420, y: 720, width: 120, height: 95, type: 'tent', obstacleHeight: 100, canVault: false },
  { id: 'tent_scout', x: 920, y: 740, width: 115, height: 90, type: 'tent', obstacleHeight: 95, canVault: false },
  
  // Campsite Campfire Pit (Low stone ring - Vaultable!)
  { id: 'campfire_pit_obs', x: 680, y: 640, width: 60, height: 60, shape: 'circle', radius: 32, type: 'campfire_base', obstacleHeight: 20, canVault: true },

  // Campsite Perimeter Fences (Vaultable!)
  { id: 'fence_camp_north_1', x: 320, y: 360, width: 180, height: 18, type: 'fence', obstacleHeight: 30, canVault: true },
  { id: 'fence_camp_north_2', x: 740, y: 360, width: 180, height: 18, type: 'fence', obstacleHeight: 30, canVault: true },
  { id: 'fence_camp_west_1', x: 320, y: 380, width: 18, height: 260, type: 'fence', obstacleHeight: 30, canVault: true },

  // Vaultable Mossy Fallen Pine Logs in Deep Forest
  { id: 'log_forest_1', x: 1020, y: 1780, width: 140, height: 32, type: 'log', obstacleHeight: 24, canVault: true },
  { id: 'log_forest_2', x: 1380, y: 2320, width: 160, height: 34, type: 'log', obstacleHeight: 24, canVault: true },
  { id: 'log_forest_3', x: 720, y: 2560, width: 150, height: 32, type: 'log', obstacleHeight: 24, canVault: true },
  { id: 'log_forest_4', x: 1840, y: 1820, width: 130, height: 32, type: 'log', obstacleHeight: 24, canVault: true },

  // Big Forest Boulders & Rock Formations (High vs Low)
  { id: 'rock_forest_1', x: 260, y: 380, width: 80, height: 70, shape: 'circle', radius: 38, type: 'rock', obstacleHeight: 50, canVault: true },
  { id: 'rock_forest_2', x: 1250, y: 420, width: 100, height: 80, shape: 'circle', radius: 46, type: 'rock', obstacleHeight: 60, canVault: true },
  { id: 'rock_forest_3', x: 1520, y: 920, width: 110, height: 85, shape: 'circle', radius: 50, type: 'rock', obstacleHeight: 65, canVault: true },
  { id: 'rock_forest_4', x: 480, y: 1950, width: 90, height: 75, shape: 'circle', radius: 42, type: 'rock', obstacleHeight: 55, canVault: true },
  { id: 'rock_forest_5', x: 1450, y: 2450, width: 120, height: 95, shape: 'circle', radius: 55, type: 'rock', obstacleHeight: 70, canVault: true },

  // Mountain & Canyon Massive Cliffs (Impassable Rock Ridges / Walls unless on plateau)
  { id: 'cliff_canyon_north_1', x: 2400, y: 460, width: 450, height: 40, type: 'cliff', elevationZ: 0, obstacleHeight: 140, canVault: false },
  { id: 'cliff_canyon_north_2', x: 3100, y: 460, width: 520, height: 40, type: 'cliff', elevationZ: 0, obstacleHeight: 140, canVault: false },
  { id: 'cliff_canyon_south_ridge_1', x: 2350, y: 1060, width: 520, height: 40, type: 'cliff', elevationZ: 0, obstacleHeight: 140, canVault: false },
  { id: 'cliff_canyon_south_ridge_2', x: 3100, y: 1060, width: 620, height: 40, type: 'cliff', elevationZ: 0, obstacleHeight: 140, canVault: false },

  // High Mountain Arena Plateau Walls & Summit Ridge
  { id: 'cliff_summit_wall_left', x: 2840, y: 1800, width: 40, height: 480, type: 'cliff', elevationZ: 0, obstacleHeight: 120, canVault: false },
  { id: 'cliff_summit_wall_right', x: 4560, y: 1800, width: 40, height: 1100, type: 'cliff', elevationZ: 0, obstacleHeight: 120, canVault: false },
  { id: 'cliff_summit_wall_back', x: 2850, y: 2980, width: 1720, height: 40, type: 'cliff', elevationZ: 0, obstacleHeight: 120, canVault: false },
  { id: 'boulder_arena_1', x: 3350, y: 2150, width: 90, height: 80, shape: 'circle', radius: 44, type: 'rock', elevationZ: 120, obstacleHeight: 50, canVault: true },
  { id: 'boulder_arena_2', x: 4050, y: 2450, width: 95, height: 85, shape: 'circle', radius: 46, type: 'rock', elevationZ: 120, obstacleHeight: 50, canVault: true },

  // ==========================================
  // URBAN WARZONE OBSTACLES: CARS, DUMPSTERS, BARRICADES & SKYSCRAPER WALLS
  // ==========================================
  // Police Cruiser Squad Cars (Vaultable hoods & roofs!)
  { id: 'car_police_1', x: 740, y: 3640, width: 100, height: 50, type: 'wall', obstacleHeight: 35, canVault: true },
  { id: 'car_police_2', x: 1620, y: 3640, width: 100, height: 50, type: 'wall', obstacleHeight: 35, canVault: true },

  // Cyber Gang Muscle Cars (Vaultable!)
  { id: 'car_punk_1', x: 3550, y: 3670, width: 110, height: 52, type: 'wall', obstacleHeight: 35, canVault: true },
  { id: 'car_punk_2', x: 4400, y: 3670, width: 110, height: 52, type: 'wall', obstacleHeight: 35, canVault: true },

  // City Heavy Dumpsters (Vaultable!)
  { id: 'dumpster_1', x: 1520, y: 3580, width: 68, height: 44, type: 'crate', obstacleHeight: 38, canVault: true },
  { id: 'dumpster_2', x: 3750, y: 3600, width: 68, height: 44, type: 'crate', obstacleHeight: 38, canVault: true },

  // Spiked Tire Barricades (Vaultable!)
  { id: 'tire_barricade_1', x: 3000, y: 3600, width: 120, height: 30, type: 'fence', obstacleHeight: 28, canVault: true },
  { id: 'tire_barricade_2', x: 4150, y: 3600, width: 120, height: 30, type: 'fence', obstacleHeight: 28, canVault: true },

  // Faction Barricades, Sandbags, Concrete Walls
  { id: 'cop_barricade_1', x: 2100, y: 3400, width: 40, height: 180, type: 'wall', obstacleHeight: 36, canVault: true },
  { id: 'cop_barricade_2', x: 2100, y: 3800, width: 40, height: 200, type: 'wall', obstacleHeight: 36, canVault: true },
  { id: 'cop_sandbags_1', x: 1900, y: 3250, width: 140, height: 40, type: 'wall', obstacleHeight: 28, canVault: true },
  { id: 'cop_sandbags_2', x: 1900, y: 4050, width: 140, height: 40, type: 'wall', obstacleHeight: 28, canVault: true },
  { id: 'punk_barricade_1', x: 2900, y: 3400, width: 40, height: 180, type: 'wall', obstacleHeight: 36, canVault: true },
  { id: 'punk_barricade_2', x: 2900, y: 3800, width: 40, height: 200, type: 'wall', obstacleHeight: 36, canVault: true },
  { id: 'punk_sandbags_1', x: 3000, y: 3250, width: 140, height: 40, type: 'wall', obstacleHeight: 28, canVault: true },
  { id: 'punk_sandbags_2', x: 3000, y: 4050, width: 140, height: 40, type: 'wall', obstacleHeight: 28, canVault: true },
  { id: 'warzone_middle_bunker', x: 2450, y: 3600, width: 100, height: 80, type: 'wall', obstacleHeight: 90, canVault: false },
  { id: 'warzone_north_pillbox', x: 2450, y: 3250, width: 90, height: 70, type: 'wall', obstacleHeight: 90, canVault: false },
  { id: 'warzone_south_pillbox', x: 2450, y: 4050, width: 90, height: 70, type: 'wall', obstacleHeight: 90, canVault: false },

];

// INTERACTIVE OBJECTS (Explosive Barrels, Caches, and HOSTINGOVAYA Smashable Server Racks)
export const INITIAL_INTERACTIVE_OBJECTS: InteractiveObject[] = [
  // Campsite perimeter defense barrels
  { id: 'barrel_camp_1', type: 'explosive_barrel', x: 1150, y: 620, hp: 30, maxHp: 30, radius: 20 },
  { id: 'barrel_camp_2', type: 'explosive_barrel', x: 1220, y: 880, hp: 30, maxHp: 30, radius: 20 },

  // Canyon pass ambush barrels
  { id: 'barrel_canyon_1', type: 'explosive_barrel', x: 2250, y: 680, hp: 30, maxHp: 30, radius: 20 },
  { id: 'barrel_canyon_2', type: 'explosive_barrel', x: 2320, y: 650, hp: 30, maxHp: 30, radius: 20 },

  // =========================================================
  // HOSTINGOVAYA SMASHABLE SERVERS & QUANTUM CORE
  // =========================================================
  // HOSTINGOVAYA smashables live on teleport interiors (x ≥ 6800)
  { id: 'server_f1_1', name: 'Web Server Rack #1', type: 'server_rack', x: (getInteriorRoom('bldg_hostingovaya', 0, 'Net closet')?.x ?? 9400) + 50, y: (getInteriorRoom('bldg_hostingovaya', 0, 'Net closet')?.y ?? 350) + 50, elevationZ: 0, rackLevel: 1, buildingId: 'bldg_hostingovaya', floorIndex: 0, hp: 60, maxHp: 60, radius: 24 },
  { id: 'server_f1_2', name: 'Database Server Rack #2', type: 'server_rack', x: (getInteriorRoom('bldg_hostingovaya', 0, 'Net closet')?.x ?? 9400) + 110, y: (getInteriorRoom('bldg_hostingovaya', 0, 'Net closet')?.y ?? 350) + 50, elevationZ: 0, rackLevel: 1, buildingId: 'bldg_hostingovaya', floorIndex: 0, hp: 60, maxHp: 60, radius: 24 },
  { id: 'server_f1_3', name: 'DNS Router Rack #3', type: 'server_rack', x: (getInteriorRoom('bldg_hostingovaya', 0, 'Net closet')?.x ?? 9400) + 50, y: (getInteriorRoom('bldg_hostingovaya', 0, 'Net closet')?.y ?? 350) + 110, elevationZ: 0, rackLevel: 1, buildingId: 'bldg_hostingovaya', floorIndex: 0, hp: 60, maxHp: 60, radius: 24 },

  { id: 'server_f2_1', name: 'Cloud NVMe Storage Rack #4', type: 'server_rack', x: (getInteriorRoom('bldg_hostingovaya', 1, 'Aisle A')?.x ?? 9400) + 50, y: (getInteriorRoom('bldg_hostingovaya', 1, 'Aisle A')?.y ?? 1300) + 50, elevationZ: 0, rackLevel: 2, buildingId: 'bldg_hostingovaya', floorIndex: 1, hp: 80, maxHp: 80, radius: 24 },
  { id: 'server_f2_2', name: '100Gbps Optical Switch Rack #5', type: 'server_rack', x: (getInteriorRoom('bldg_hostingovaya', 1, 'Aisle A')?.x ?? 9400) + 110, y: (getInteriorRoom('bldg_hostingovaya', 1, 'Aisle A')?.y ?? 1300) + 50, elevationZ: 0, rackLevel: 2, buildingId: 'bldg_hostingovaya', floorIndex: 1, hp: 80, maxHp: 80, radius: 24 },
  { id: 'server_f2_3', name: 'Firewall Array Rack #6', type: 'server_rack', x: (getInteriorRoom('bldg_hostingovaya', 1, 'Aisle B')?.x ?? 9400) + 50, y: (getInteriorRoom('bldg_hostingovaya', 1, 'Aisle B')?.y ?? 1300) + 50, elevationZ: 0, rackLevel: 2, buildingId: 'bldg_hostingovaya', floorIndex: 1, hp: 80, maxHp: 80, radius: 24 },
  { id: 'server_f2_4', name: 'Backup SAN Array #7', type: 'server_rack', x: (getInteriorRoom('bldg_hostingovaya', 1, 'Aisle B')?.x ?? 9400) + 110, y: (getInteriorRoom('bldg_hostingovaya', 1, 'Aisle B')?.y ?? 1300) + 50, elevationZ: 0, rackLevel: 2, buildingId: 'bldg_hostingovaya', floorIndex: 1, hp: 80, maxHp: 80, radius: 24 },

  { id: 'server_f3_1', name: 'RTX 5090 AI Node #8', type: 'server_rack', x: (getInteriorRoom('bldg_hostingovaya', 2, 'Cluster')?.x ?? 9400) + 50, y: (getInteriorRoom('bldg_hostingovaya', 2, 'Cluster')?.y ?? 2250) + 60, elevationZ: 0, rackLevel: 3, buildingId: 'bldg_hostingovaya', floorIndex: 2, hp: 110, maxHp: 110, radius: 24 },
  { id: 'server_f3_2', name: 'Deep Learning Cluster #9', type: 'server_rack', x: (getInteriorRoom('bldg_hostingovaya', 2, 'Cluster')?.x ?? 9400) + 110, y: (getInteriorRoom('bldg_hostingovaya', 2, 'Cluster')?.y ?? 2250) + 60, elevationZ: 0, rackLevel: 3, buildingId: 'bldg_hostingovaya', floorIndex: 2, hp: 110, maxHp: 110, radius: 24 },
  { id: 'server_f3_3', name: 'Crypto Farm Rack #10', type: 'server_rack', x: (getInteriorRoom('bldg_hostingovaya', 2, 'Cluster')?.x ?? 9400) + 170, y: (getInteriorRoom('bldg_hostingovaya', 2, 'Cluster')?.y ?? 2250) + 60, elevationZ: 0, rackLevel: 3, buildingId: 'bldg_hostingovaya', floorIndex: 2, hp: 110, maxHp: 110, radius: 24 },
  { id: 'server_f3_4', name: 'H100 Tensor Cluster #11', type: 'server_rack', x: (getInteriorRoom('bldg_hostingovaya', 2, 'Cluster')?.x ?? 9400) + 110, y: (getInteriorRoom('bldg_hostingovaya', 2, 'Cluster')?.y ?? 2250) + 160, elevationZ: 0, rackLevel: 3, buildingId: 'bldg_hostingovaya', floorIndex: 2, hp: 110, maxHp: 110, radius: 24 },

  { id: 'quantum_core_main', name: '👑 QUANTUM MAINFRAME SUPERCOMPUTER', type: 'quantum_core', x: (getInteriorRoom('bldg_hostingovaya', 3, 'Core')?.x ?? 9400) + 150, y: (getInteriorRoom('bldg_hostingovaya', 3, 'Core')?.y ?? 3200) + 140, elevationZ: 0, rackLevel: 4, buildingId: 'bldg_hostingovaya', floorIndex: 3, hp: 280, maxHp: 280, radius: 38 },

  { id: 'barrel_canyon_3', type: 'explosive_barrel', x: 2750, y: 920, hp: 30, maxHp: 30, radius: 20 },
  { id: 'barrel_canyon_4', type: 'explosive_barrel', x: 3450, y: 850, hp: 30, maxHp: 30, radius: 20 },
  { id: 'barrel_canyon_5', type: 'explosive_barrel', x: 3520, y: 890, hp: 30, maxHp: 30, radius: 20 },
  { id: 'barrel_canyon_6', type: 'explosive_barrel', x: 3950, y: 650, hp: 30, maxHp: 30, radius: 20 },

  // Summit Arena combat barrels
  { id: 'barrel_arena_1', type: 'explosive_barrel', x: 3250, y: 2050, hp: 30, maxHp: 30, radius: 20 },
  { id: 'barrel_arena_2', type: 'explosive_barrel', x: 4150, y: 2150, hp: 30, maxHp: 30, radius: 20 },
  { id: 'barrel_arena_3', type: 'explosive_barrel', x: 3700, y: 2750, hp: 30, maxHp: 30, radius: 20 },
  { id: 'barrel_arena_4', type: 'explosive_barrel', x: 3780, y: 2780, hp: 30, maxHp: 30, radius: 20 },

  // Warzone Frontline Volatile Red Barrels
  { id: 'barrel_warzone_1', type: 'explosive_barrel', x: 2350, y: 3450, hp: 30, maxHp: 30, radius: 20 },
  { id: 'barrel_warzone_2', type: 'explosive_barrel', x: 2650, y: 3450, hp: 30, maxHp: 30, radius: 20 },
  { id: 'barrel_warzone_3', type: 'explosive_barrel', x: 2400, y: 3850, hp: 30, maxHp: 30, radius: 20 },
  { id: 'barrel_warzone_4', type: 'explosive_barrel', x: 2600, y: 3850, hp: 30, maxHp: 30, radius: 20 },
  { id: 'barrel_warzone_5', type: 'explosive_barrel', x: 2150, y: 3650, hp: 30, maxHp: 30, radius: 20 },
  { id: 'barrel_warzone_6', type: 'explosive_barrel', x: 2850, y: 3650, hp: 30, maxHp: 30, radius: 20 },
];

export const ITEMS_DATABASE: Record<string, Item> = {
  // 1. Pistol (9mm Tactical Handgun / Starter)
  'wpn_starter_pistol': {
    id: 'wpn_starter_pistol',
    name: 'Tactical 9mm Pistol',
    type: 'weapon',
    gunType: 'pistol',
    rarity: 'common',
    icon: '🔫',
    description: 'Crisp semi-automatic 9mm handgun. Fast handling with pinpoint accuracy.',
    stats: { atk: 18, speed: 5, crit: 8 },
    price: 60,
  },
  'wpn_pistol': {
    id: 'wpn_pistol',
    name: 'P250 Combat Pistol',
    type: 'weapon',
    gunType: 'pistol',
    rarity: 'common',
    icon: '🔫',
    description: 'Standard issue military handgun. Reliable cadence and low recoil.',
    stats: { atk: 22, speed: 6, crit: 10 },
    price: 120,
  },

  // 2. Revolver (.44 Magnum Hand Cannon)
  'wpn_bandit_revolver': {
    id: 'wpn_bandit_revolver',
    name: '.44 Outlaw Heavy Revolver',
    type: 'weapon',
    gunType: 'revolver',
    rarity: 'rare',
    icon: '🔫',
    description: 'Massive caliber six-shooter. Thunderous blast with intense single-target impact and head knockback.',
    stats: { atk: 48, speed: 4, crit: 25 },
    price: 420,
  },
  'wpn_revolver': {
    id: 'wpn_revolver',
    name: 'Python .357 Revolver',
    type: 'weapon',
    gunType: 'revolver',
    rarity: 'rare',
    icon: '🔫',
    description: 'Polished steel magnum revolver with devastating stopping power.',
    stats: { atk: 44, speed: 5, crit: 22 },
    price: 380,
  },

  // 3. MAC-10 (Micro-SMG)
  'wpn_mac10': {
    id: 'wpn_mac10',
    name: 'MAC-10 Micro SMG',
    type: 'weapon',
    gunType: 'mac10',
    rarity: 'rare',
    icon: '💥',
    description: 'Extreme fire-rate compact submachine gun. Sprays a blistering cone of lead with flying brass.',
    stats: { atk: 17, speed: 12, crit: 12 },
    price: 550,
  },

  // 4. AK-47 (Kalash)
  'wpn_ak47': {
    id: 'wpn_ak47',
    name: 'AK-47 Kalashnikov',
    type: 'weapon',
    gunType: 'ak47',
    rarity: 'epic',
    icon: '🎯',
    description: 'Iconic assault rifle chambered in 7.62mm. High kinetic punch and superior combat range.',
    stats: { atk: 38, speed: 8, crit: 18 },
    price: 850,
  },

  // 5. Shotgun (Trench Sweeper Sawed-Off)
  'wpn_shotgun': {
    id: 'wpn_shotgun',
    name: 'Trench Sweeper Shotgun',
    type: 'weapon',
    gunType: 'shotgun',
    rarity: 'epic',
    icon: '🔥',
    description: 'Heavy 12-gauge pump shotgun. Blasts a wide 7-pellet spread that shreds close-range hostiles.',
    stats: { atk: 24, speed: 3, crit: 15 },
    price: 780,
  },

  // 6. CheyTac M200 (Intervention Sniper Rifle)
  'wpn_cheytac': {
    id: 'wpn_cheytac',
    name: 'CheyTac M200 Intervention',
    type: 'weapon',
    gunType: 'cheytac',
    rarity: 'legendary',
    icon: '⚡',
    description: 'Long-range .408 anti-materiel sniper rifle. Hyper-velocity piercing rounds with colossal critical damage!',
    stats: { atk: 140, speed: 2, crit: 45 },
    price: 2400,
  },

  // Melee & Boss Sledge
  'wpn_welder_sledge': {
    id: 'wpn_welder_sledge',
    name: 'Industrial Welder Sledgehammer',
    type: 'weapon',
    gunType: 'sledgehammer',
    rarity: 'legendary',
    icon: '🔨',
    description: 'Massive heavy hammer salvaged from "Iron Mask" Sledge. Smashes ground fissures with colossal blunt force.',
    stats: { atk: 110, def: 25, crit: 20, maxHp: 220 },
    price: 2800,
  },
  'wpn_neon_katana': {
    id: 'wpn_neon_katana',
    name: 'Muramasa Katana',
    type: 'weapon',
    gunType: 'katana',
    rarity: 'rare',
    icon: '🗡️',
    description: 'Folded-steel katana. Fast slashes, tight arcs, and bleeding follow-through.',
    stats: { atk: 36, speed: 9, crit: 18 },
    price: 320,
  },
  'wpn_throwing_knives': {
    id: 'wpn_throwing_knives',
    name: 'Kunai Fan',
    type: 'weapon',
    gunType: 'throwing_knives',
    rarity: 'rare',
    icon: '🔪',
    description: 'A belt of throwing knives. Snap them at range — they fly fast and stick deep.',
    stats: { atk: 28, speed: 11, crit: 22 },
    price: 280,
  },
  'wpn_reaper_scythe': {
    id: 'wpn_reaper_scythe',
    name: 'Reaper Scythe',
    type: 'weapon',
    gunType: 'scythe',
    rarity: 'epic',
    icon: '🪓',
    description: 'A huge hooked axe-scythe. Slow crescent sweeps that yank a whole crowd.',
    stats: { atk: 52, speed: 4, crit: 14 },
    price: 720,
  },
  'wpn_greatsword': {
    id: 'wpn_greatsword',
    name: 'Zweihander',
    type: 'weapon',
    gunType: 'greatsword',
    rarity: 'legendary',
    icon: '⚔️',
    description: 'Absurdly long two-handed greatsword. Heavy overhead slams with a crushing reach.',
    stats: { atk: 78, speed: 2, crit: 20 },
    price: 1100,
  },
  'wpn_arcane_staff': {
    id: 'wpn_arcane_staff',
    name: 'Inferno Staff',
    type: 'weapon',
    gunType: 'staff',
    rarity: 'rare',
    icon: '🔥',
    description: 'Channels compact fireballs that detonate on impact.',
    stats: { atk: 34, speed: 6, crit: 12 },
    price: 400,
  },
  'wpn_chaos_wand': {
    id: 'wpn_chaos_wand',
    name: 'Spark Wand',
    type: 'weapon',
    gunType: 'wand',
    rarity: 'rare',
    icon: '✨',
    description: 'Automatic particle sprayer. Holds the beam and vomits glittering shards.',
    stats: { atk: 18, speed: 12, crit: 10 },
    price: 360,
  },
  'wpn_grimoire': {
    id: 'wpn_grimoire',
    name: 'Void Grimoire',
    type: 'weapon',
    gunType: 'grimoire',
    rarity: 'epic',
    icon: '🔮',
    description: 'Launches a black hole that pulls nearby enemies in and collapses in a void explosion.',
    stats: { atk: 64, speed: 3, crit: 16 },
    price: 880,
  },
  'wpn_summon_totem': {
    id: 'wpn_summon_totem',
    name: 'Storm Totem',
    type: 'weapon',
    gunType: 'totem',
    rarity: 'epic',
    icon: '⚡',
    description: 'Places a static totem that periodically shocks multiple nearby enemies with chain lightning.',
    stats: { atk: 40, speed: 5, crit: 14 },
    price: 640,
  },

  // Headwear & Survival Gear
  'head_welder_mask': {
    id: 'head_welder_mask',
    name: 'Heavy Welder Steel Visor',
    type: 'headwear',
    rarity: 'epic',
    icon: '🥽',
    description: 'Heavy plate welder helmet with narrow eye slit. Grants massive armor and blast resistance.',
    stats: { def: 28, maxHp: 160, atk: 12 },
    price: 650,
  },
  'head_outlaw_stetson': {
    id: 'head_outlaw_stetson',
    name: 'Outlaw Bandit Hat',
    type: 'headwear',
    rarity: 'rare',
    icon: '🤠',
    description: 'Weathered leather hat. Increases quick-draw agility and critical hit chance.',
    stats: { def: 14, crit: 12, speed: 5 },
    price: 320,
  },
  'head_cat_band': {
    id: 'head_cat_band',
    name: 'Survivor Headband',
    type: 'headwear',
    rarity: 'common',
    icon: '🎀',
    description: 'Comfortable cloth band that keeps sweat and dust out of your eyes.',
    stats: { def: 8, speed: 4, maxHp: 40 },
    price: 75,
  },

  // Outfits
  'outfit_leather_vest': {
    id: 'outfit_leather_vest',
    name: 'Reinforced Combat Trench',
    type: 'outfit',
    rarity: 'rare',
    icon: '🧥',
    description: 'Heavy tactical coat with kevlar lining and ammo bandoliers.',
    stats: { def: 24, maxHp: 140, speed: 3 },
    price: 450,
  },
  'outfit_cyber_hoodie': {
    id: 'outfit_cyber_hoodie',
    name: 'Survivor Field Parka',
    type: 'outfit',
    rarity: 'common',
    icon: '🥋',
    description: 'Insulated outdoor jacket for deep wilderness exploration.',
    stats: { def: 12, maxHp: 60 },
    price: 150,
  },

  // Vehicles
  'veh_skateboard': {
    id: 'veh_skateboard',
    name: 'Off-Road Timber Skateboard',
    type: 'vehicle',
    rarity: 'common',
    icon: '🛹',
    description: 'Kickflip on [V] to hop on. Jump = kickflip, dash = ollie, air dash = tre flip. Style points pay gold.',
    vehicleSpeed: 25,
    vehicleType: 'skateboard',
    price: 100,
  },
  'veh_hoverboard': {
    id: 'veh_hoverboard',
    name: 'Mag-Lev Desert Hoverboard',
    type: 'vehicle',
    rarity: 'rare',
    icon: '🛸',
    description: 'Glides seamlessly across rocks, mud, and water puddles.',
    vehicleSpeed: 45,
    vehicleType: 'hoverboard',
    price: 600,
  },

  // Consumables
  'item_soul_ember': {
    id: 'item_soul_ember',
    name: 'Soul Ember',
    type: 'material',
    rarity: 'uncommon',
    icon: '◆',
    description: 'A condensed soul spark. Magnetizes to the survivor and grants EXP.',
    price: 0,
    stackable: true,
  },

  'item_hp_potion_s': {
    id: 'item_hp_potion_s',
    name: 'Military Field Medkit',
    type: 'consumable',
    rarity: 'common',
    icon: '🩹',
    description: 'Emergency gauze and adrenaline. Instantly restores 180 HP.',
    healHp: 180,
    price: 25,
    stackable: true,
  },
  'item_hp_potion_l': {
    id: 'item_hp_potion_l',
    name: 'Surgeon Trauma Kit',
    type: 'consumable',
    rarity: 'rare',
    icon: '💉',
    description: 'Advanced medical kit. Restores 500 HP.',
    healHp: 500,
    price: 75,
    stackable: true,
  },
  'item_ramen_bowl': {
    id: 'item_ramen_bowl',
    name: 'Campfire Stew & Rations',
    type: 'consumable',
    rarity: 'rare',
    icon: '🍲',
    description: 'Hearty campfire stew. Grants +30% Attack Power for 5 minutes.',
    buffDuration: 300,
    buffType: 'atk',
    buffValue: 30,
    healHp: 250,
    price: 90,
    stackable: true,
  },

  // Materials & Gatherables
  'mat_wood': {
    id: 'mat_wood',
    name: 'Pine Timber Log',
    type: 'material',
    rarity: 'common',
    icon: '🪵',
    description: 'Dense fragrant pine timber chopped in the forest.',
    price: 5,
    stackable: true,
  },
  'mat_iron_ore': {
    id: 'mat_iron_ore',
    name: 'Raw Iron Ore',
    type: 'material',
    rarity: 'common',
    icon: '🪨',
    description: 'Heavy raw iron mined from rocky canyon crags.',
    price: 8,
    stackable: true,
  },
  'mat_lumite_crystal': {
    id: 'mat_lumite_crystal',
    name: 'Luminescent Crystal',
    type: 'material',
    rarity: 'rare',
    icon: '💎',
    description: 'Glowing crystal discovered in deep forest hollows.',
    price: 25,
    stackable: true,
  },
  'mat_outlaw_badge': {
    id: 'mat_outlaw_badge',
    name: 'Bandit Dogtag / Badge',
    type: 'material',
    rarity: 'rare',
    icon: '⭐',
    description: 'Engraved skull insignia collected from defeated bandits.',
    price: 30,
    stackable: true,
  },
  'mat_welder_scrap': {
    id: 'mat_welder_scrap',
    name: 'Forged Titanium Ingot',
    type: 'material',
    rarity: 'epic',
    icon: '⚙️',
    description: 'Super-hardened alloy forged by "Iron Mask" Sledge.',
    price: 150,
    stackable: true,
  },
};

export const CRAFT_RECIPES: CraftRecipe[] = [
  {
    id: 'recipe_ak47',
    name: 'AK-47 Kalashnikov',
    category: 'weapons',
    resultItemId: 'wpn_ak47',
    resultQuantity: 1,
    unlockLevel: 3,
    materials: [
      { itemId: 'mat_iron_ore', count: 10 },
      { itemId: 'mat_wood', count: 6 },
      { itemId: 'mat_outlaw_badge', count: 4 },
    ],
  },
  {
    id: 'recipe_shotgun',
    name: 'Trench Sweeper Shotgun',
    category: 'weapons',
    resultItemId: 'wpn_shotgun',
    resultQuantity: 1,
    unlockLevel: 2,
    materials: [
      { itemId: 'mat_iron_ore', count: 8 },
      { itemId: 'mat_wood', count: 5 },
    ],
  },
  {
    id: 'recipe_cheytac',
    name: 'CheyTac M200 Intervention',
    category: 'weapons',
    resultItemId: 'wpn_cheytac',
    resultQuantity: 1,
    unlockLevel: 5,
    materials: [
      { itemId: 'mat_welder_scrap', count: 3 },
      { itemId: 'mat_iron_ore', count: 15 },
      { itemId: 'mat_lumite_crystal', count: 8 },
    ],
  },
  {
    id: 'recipe_medkit',
    name: 'Surgeon Trauma Kit',
    category: 'potions',
    resultItemId: 'item_hp_potion_l',
    resultQuantity: 2,
    unlockLevel: 1,
    materials: [
      { itemId: 'mat_lumite_crystal', count: 2 },
      { itemId: 'item_hp_potion_s', count: 2 },
    ],
  },
];

export const INITIAL_RESOURCE_NODES: ResourceNode[] = [
  // Camp & Forest Trees
  { id: 'node_tree_1', type: 'tree', name: 'Dense Pine Tree', x: 380, y: 320, hp: 30, maxHp: 30, dropItemId: 'mat_wood' },
  { id: 'node_tree_2', type: 'tree', name: 'Dense Pine Tree', x: 1050, y: 350, hp: 30, maxHp: 30, dropItemId: 'mat_wood' },
  { id: 'node_tree_3', type: 'tree', name: 'Dense Pine Tree', x: 1420, y: 550, hp: 30, maxHp: 30, dropItemId: 'mat_wood' },
  { id: 'node_tree_4', type: 'tree', name: 'Ancient Pine', x: 500, y: 1800, hp: 35, maxHp: 35, dropItemId: 'mat_wood' },
  { id: 'node_tree_5', type: 'tree', name: 'Ancient Pine', x: 950, y: 2200, hp: 35, maxHp: 35, dropItemId: 'mat_wood' },

  // Canyon & Crag Iron Ore Deposits
  { id: 'node_ore_1', type: 'iron_ore', name: 'Canyon Iron Vein', x: 2150, y: 350, hp: 45, maxHp: 45, dropItemId: 'mat_iron_ore' },
  { id: 'node_ore_2', type: 'iron_ore', name: 'Crag Iron Vein', x: 2900, y: 450, hp: 45, maxHp: 45, dropItemId: 'mat_iron_ore' },
  { id: 'node_ore_3', type: 'iron_ore', name: 'High Peak Iron Vein', x: 3650, y: 550, hp: 45, maxHp: 45, dropItemId: 'mat_iron_ore' },

  // Deep Woods Lumite Crystal Clusters
  { id: 'node_lumite_1', type: 'lumite_crystal', name: 'Lumite Glow Cluster', x: 750, y: 2550, hp: 50, maxHp: 50, dropItemId: 'mat_lumite_crystal' },
  { id: 'node_lumite_2', type: 'lumite_crystal', name: 'Lumite Glow Cluster', x: 1350, y: 2700, hp: 50, maxHp: 50, dropItemId: 'mat_lumite_crystal' },
];

export const NPCS_DATABASE: Record<string, NPC> = {
  'npc_hank_guide': {
    id: 'npc_hank_guide',
    name: 'Doc "Hank" Vance',
    title: 'Camp Commander & Medic',
    avatarChibi: {
      hairStyle: 'short_messy',
      hairColor: '#374151',
      earType: 'none',
      earColor: '#1F2937',
      haloType: 'none',
      haloColor: '#E2E8F0',
      coatColor: '#1E293B',
      skirtColor: '#334155',
      eyeType: 'determined',
      ribbonColor: '#DC2626',
    },
    role: 'quest',
    x: 650,
    y: 520, // Standing outside the main HQ tent
    dialogue: {
      greeting: "Glad you made it back to camp in one piece, kid. The outlaws are crawling all over the eastern canyon pass. If you're heading out, keep your finger on the trigger!",
      options: [
        { text: 'View Outpost Quests', action: 'open_quests' },
        { text: 'Treat my wounds (Heal)', action: 'heal', dialogueText: 'Here, have some sterile gauze and adrenaline. You are back at full combat strength!' },
        { text: 'Tell me about the Welder Boss', action: 'talk', dialogueText: 'Up at the high rocky crag lives "Iron Mask" Sledge. Big guy in a welding visor wielding a colossal hammer. Watch out when he slams the ground or calls his grunts!' },
      ],
    },
    questIds: ['quest_camp_security', 'quest_canyon_purge', 'quest_welder_bounty'],
  },

  'npc_seraph_smith': {
    id: 'npc_seraph_smith',
    name: 'Sarge Steel',
    title: 'Weaponsmith & Armorer',
    avatarChibi: {
      hairStyle: 'spiky',
      hairColor: '#D97706',
      earType: 'none',
      earColor: '#78350F',
      haloType: 'none',
      haloColor: '#F59E0B',
      coatColor: '#451A03',
      skirtColor: '#78350F',
      eyeType: 'smug',
      ribbonColor: '#F59E0B',
    },
    role: 'craft',
    x: 880,
    y: 540, // Next to the armory tent & anvil
    dialogue: {
      greeting: "Need some real firepower? Bring me raw iron ore, pine timber, and bandit dogtags, and I'll assemble Kalashnikovs, shotguns, and precision CheyTac snipers.",
      options: [
        { text: 'Open Weapon Workshop', action: 'open_craft' },
        { text: 'Browse Arsenal Shop', action: 'open_shop' },
      ],
    },
    craftRecipeIds: ['recipe_ak47', 'recipe_shotgun', 'recipe_cheytac', 'recipe_medkit'],
    shopItemIds: ['wpn_pistol', 'wpn_revolver', 'wpn_mac10', 'wpn_ak47', 'wpn_shotgun', 'item_hp_potion_s', 'item_hp_potion_l'],
  },

  'npc_momoi_guide': {
    id: 'npc_momoi_guide',
    name: 'Arona & Momoi',
    title: 'Camp Scout & Recon',
    avatarChibi: {
      hairStyle: 'twintails',
      hairColor: '#F472B6',
      earType: 'cat',
      earColor: '#BE185D',
      haloType: 'circle',
      haloColor: '#FB7185',
      coatColor: '#1E293B',
      skirtColor: '#475569',
      eyeType: 'happy',
      ribbonColor: '#F43F5E',
    },
    role: 'guide',
    x: 640,
    y: 720, // Sitting by the glowing campfire log
    dialogue: {
      greeting: "Warm up by the fire! Tip: Holding Space chains fast bunny hops to dodge enemy bullets! Defeated enemies also drop their weapons directly on the ground so you can swap your loadout anytime.",
      options: [
        { text: 'How do guns & weapons work?', action: 'talk', dialogueText: 'You can carry all 6 weapons (Pistol, Revolver, MAC-10, AK-47, Shotgun, CheyTac). Press [1]-[6] or click the weapon dock to switch instantly! Shoot red explosive barrels to wipe out crowds.' },
        { text: 'How do bunny hops work?', action: 'talk', dialogueText: 'Just hold [Space] while moving! You will continuously bounce forward and build up massive speed stacks.' },
      ],
    },
  },

  'npc_chibi_cafe': {
    id: 'npc_chibi_cafe',
    name: 'Luna',
    title: 'Camp Cook & Supplies',
    avatarChibi: {
      hairStyle: 'braids',
      hairColor: '#FB7185',
      earType: 'bunny',
      earColor: '#9F1239',
      haloType: 'none',
      haloColor: '#F43F5E',
      coatColor: '#FFF1F2',
      skirtColor: '#881337',
      eyeType: 'wink',
      ribbonColor: '#E11D48',
    },
    role: 'cafe',
    x: 440,
    y: 770, // In the kitchen tent
    dialogue: {
      greeting: "Hey survivor! Got hot campfire stew ready to give you +30% attack strength, along with field medkits and off-road boards!",
      options: [
        { text: 'Buy Rations & Gear', action: 'open_shop' },
      ],
    },
    shopItemIds: ['item_ramen_bowl', 'item_hp_potion_s', 'item_hp_potion_l', 'veh_skateboard', 'veh_hoverboard'],
  },

  'npc_nyx_crucible': {
    id: 'npc_nyx_crucible',
    name: 'Nyx',
    title: 'Nullspace Gatekeeper',
    avatarChibi: {
      hairStyle: 'hime_cut',
      hairColor: '#6D28D9',
      earType: 'none',
      earColor: '#1E1B4B',
      haloType: 'circle',
      haloColor: '#C4B5FD',
      coatColor: '#1E1B4B',
      skirtColor: '#4C1D95',
      eyeType: 'determined',
      ribbonColor: '#A855F7',
    },
    role: 'guide',
    x: 980,
    y: 620,
    dialogue: {
      greeting: "За костром дыра в стойку. Не волны — бесконечное мясо. Каждые 20 секунд в грид вползает новый тип. Каждую минуту — босс. Лазеры чертят пол, с неба сыпется кластер, иногда кто-то выключает тебе глаза. Выйдешь по [T] с добычей. Сдохнешь — обратно к костру. Готов?",
      options: [
        { text: 'Войти в Nullspace', action: 'enter_horde' },
        { text: 'Как это работает?', action: 'talk', dialogueText: 'Это карман серверной: провалы, утечки, стойки. Мобы идут нон-стопом, каждые 20 сек новый вид, каждую минуту босс. Жёлтые души магнитятся. Луч рисуется заранее — отойди. Метки с неба — выйди из круга. Если мир погас — убей кастера или пережди пару секунд. [T] эвакуация после ~24 сек. Опыт с гемов остаётся даже если сдохнешь.' },
        { text: 'Позже', action: 'close' },
      ],
    },
  },
};

export const QUESTS_DATABASE: Record<string, Quest> = {
  'quest_camp_security': {
    id: 'quest_camp_security',
    title: 'Campsite Perimeter Defense',
    giverNpcId: 'npc_hank_guide',
    description: 'Clear the aggressive wolves and bandit grunts probing the forest camp borders.',
    minLevel: 1,
    objectives: [
      { type: 'kill', targetId: 'forest_wolf', targetName: 'Feral Wolves', current: 0, required: 3 },
      { type: 'kill', targetId: 'bandit_grunt', targetName: 'Bandit Grunts', current: 0, required: 3 },
    ],
    rewardExp: 200,
    rewardGold: 180,
    rewardItems: [
      { itemId: 'wpn_pistol', quantity: 1 },
      { itemId: 'item_hp_potion_s', quantity: 3 },
    ],
  },
  'quest_canyon_purge': {
    id: 'quest_canyon_purge',
    title: 'Canyon Pass Raid',
    giverNpcId: 'npc_hank_guide',
    description: 'Advance into the rocky canyon pass, eliminate outlaw gunslingers, and take down Viktor.',
    minLevel: 2,
    objectives: [
      { type: 'kill', targetId: 'bandit_scout', targetName: 'Outlaw Pistoleros', current: 0, required: 3 },
      { type: 'kill', targetId: 'boss_outlaw_viktor', targetName: 'Dead-Eye Viktor', current: 0, required: 1 },
    ],
    rewardExp: 600,
    rewardGold: 600,
    rewardItems: [
      { itemId: 'wpn_ak47', quantity: 1 },
      { itemId: 'item_hp_potion_l', quantity: 2 },
    ],
  },
  'quest_welder_bounty': {
    id: 'quest_welder_bounty',
    title: 'Bounty: "Iron Mask" Sledge',
    giverNpcId: 'npc_hank_guide',
    description: 'Ascend to the high mountain summit and vanquish the brutal hammer boss "Iron Mask" Sledge!',
    minLevel: 4,
    objectives: [
      { type: 'kill', targetId: 'boss_welder', targetName: '"Iron Mask" Sledge (Boss)', current: 0, required: 1 },
    ],
    rewardExp: 1500,
    rewardGold: 2000,
    rewardItems: [
      { itemId: 'wpn_cheytac', quantity: 1 },
      { itemId: 'head_welder_mask', quantity: 1 },
    ],
  },
};

export const INITIAL_MONSTERS: Monster[] = [
  // Forest Feral Wolves
  {
    id: 'mob_wolf_1',
    name: 'Shadowfang Wolf',
    type: 'forest_wolf',
    zone: 'deep_forest',
    x: 650,
    y: 1900,
    spawnX: 650,
    spawnY: 1900,
    maxHp: 90,
    hp: 90,
    atk: 14,
    def: 4,
    speed: 2.3,
    expReward: 45,
    goldReward: 30,
    state: 'idle',
    targetPlayerId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'item_hp_potion_s', chance: 0.6, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'mob_wolf_2',
    name: 'Shadowfang Wolf',
    type: 'forest_wolf',
    zone: 'deep_forest',
    x: 1200,
    y: 2300,
    spawnX: 1200,
    spawnY: 2300,
    maxHp: 90,
    hp: 90,
    atk: 14,
    def: 4,
    speed: 2.3,
    expReward: 45,
    goldReward: 30,
    state: 'idle',
    targetPlayerId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'item_hp_potion_s', chance: 0.6, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },

  // Sparring / Practice Cadets at Camp Outskirts
  {
    id: 'target_human_1',
    name: 'Sparring Partner (Brawler)',
    type: 'cadet_bat',
    zone: 'forest_camp',
    x: 1350,
    y: 650,
    spawnX: 1350,
    spawnY: 650,
    maxHp: 180,
    hp: 180,
    atk: 10,
    def: 4,
    speed: 1.9,
    expReward: 35,
    goldReward: 25,
    isHumanoid: true,
    weaponType: 'bat',
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_pistol', chance: 0.4, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_s', chance: 0.8, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },

  // CANYON & FOOTHILLS BANDIT OUTLAWS (Madness Combat Style Gunfighters)
  {
    id: 'bandit_grunt_1',
    name: 'Bandit Grunt (Club & Cleaver)',
    type: 'bandit_grunt',
    zone: 'rocky_canyon',
    x: 2150,
    y: 750,
    spawnX: 2150,
    spawnY: 750,
    maxHp: 160,
    hp: 160,
    atk: 18,
    def: 6,
    speed: 2.4,
    expReward: 60,
    goldReward: 50,
    isHumanoid: true,
    weaponType: 'bat',
    humanChibi: {
      hairStyle: 'spiky',
      hairColor: '#DC2626',
      earType: 'none',
      earColor: '#7F1D1D',
      haloType: 'cross',
      haloColor: '#EF4444',
      coatColor: '#334155',
      skirtColor: '#1E293B',
      eyeType: 'determined',
      ribbonColor: '#DC2626',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_pistol', chance: 0.45, minQty: 1, maxQty: 1 },
      { itemId: 'mat_outlaw_badge', chance: 0.8, minQty: 1, maxQty: 2 },
      { itemId: 'item_hp_potion_s', chance: 0.6, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'bandit_grunt_2',
    name: 'Bandit Grunt (Club & Cleaver)',
    type: 'bandit_grunt',
    zone: 'rocky_canyon',
    x: 2450,
    y: 920,
    spawnX: 2450,
    spawnY: 920,
    maxHp: 160,
    hp: 160,
    atk: 18,
    def: 6,
    speed: 2.4,
    expReward: 60,
    goldReward: 50,
    isHumanoid: true,
    weaponType: 'bat',
    humanChibi: {
      hairStyle: 'short_messy',
      hairColor: '#B91C1C',
      earType: 'none',
      earColor: '#7F1D1D',
      haloType: 'none',
      haloColor: '#EF4444',
      coatColor: '#1E293B',
      skirtColor: '#0F172A',
      eyeType: 'determined',
      ribbonColor: '#DC2626',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_mac10', chance: 0.35, minQty: 1, maxQty: 1 },
      { itemId: 'mat_outlaw_badge', chance: 0.8, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'bandit_scout_1',
    name: 'Outlaw Pistolero (Revolver)',
    type: 'bandit_scout',
    zone: 'rocky_canyon',
    x: 2650,
    y: 650,
    spawnX: 2650,
    spawnY: 650,
    maxHp: 180,
    hp: 180,
    atk: 22,
    def: 6,
    speed: 2.1,
    expReward: 75,
    goldReward: 65,
    isHumanoid: true,
    weaponType: 'revolver',
    humanChibi: {
      hairStyle: 'wavy',
      hairColor: '#F97316',
      earType: 'none',
      earColor: '#7C2D12',
      haloType: 'cross',
      haloColor: '#EA580C',
      coatColor: '#451A03',
      skirtColor: '#78350F',
      eyeType: 'smug',
      ribbonColor: '#F97316',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_bandit_revolver', chance: 0.4, minQty: 1, maxQty: 1 },
      { itemId: 'mat_outlaw_badge', chance: 0.85, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'bandit_shotgunner_1',
    name: 'Trench Shotgunner (Heavy)',
    type: 'bandit_shotgunner',
    zone: 'rocky_canyon',
    x: 3200,
    y: 880,
    spawnX: 3200,
    spawnY: 880,
    maxHp: 280,
    hp: 280,
    atk: 28,
    def: 12,
    speed: 1.8,
    expReward: 120,
    goldReward: 110,
    isHumanoid: true,
    weaponType: 'shotgun',
    humanChibi: {
      hairStyle: 'long_flowing',
      hairColor: '#4B5563',
      earType: 'none',
      earColor: '#1F2937',
      haloType: 'cyber_hex',
      haloColor: '#E11D48',
      coatColor: '#18181B',
      skirtColor: '#27272A',
      eyeType: 'determined',
      ribbonColor: '#E11D48',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_shotgun', chance: 0.45, minQty: 1, maxQty: 1 },
      { itemId: 'mat_outlaw_badge', chance: 0.9, minQty: 2, maxQty: 3 },
      { itemId: 'item_hp_potion_s', chance: 0.8, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'bandit_sniper_1',
    name: 'Outlaw Sniper (CheyTac)',
    type: 'bandit_sniper',
    zone: 'rocky_canyon',
    x: 3750,
    y: 520,
    spawnX: 3750,
    spawnY: 520,
    maxHp: 200,
    hp: 200,
    atk: 36,
    def: 8,
    speed: 1.7,
    expReward: 140,
    goldReward: 130,
    isHumanoid: true,
    weaponType: 'cheytac',
    humanChibi: {
      hairStyle: 'wolf_cut',
      hairColor: '#10B981',
      earType: 'none',
      earColor: '#065F46',
      haloType: 'star',
      haloColor: '#34D399',
      coatColor: '#064E3B',
      skirtColor: '#022C22',
      eyeType: 'determined',
      ribbonColor: '#10B981',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_cheytac', chance: 0.25, minQty: 1, maxQty: 1 },
      { itemId: 'wpn_ak47', chance: 0.35, minQty: 1, maxQty: 1 },
      { itemId: 'mat_outlaw_badge', chance: 1.0, minQty: 2, maxQty: 4 },
    ],
    animTimer: 0,
  },

  // MINIBOSS: "Dead-Eye" Viktor (Canyon Overlook)
  {
    id: 'boss_outlaw_viktor',
    name: 'Outlaw Warlord "Dead-Eye Viktor"',
    type: 'boss_outlaw_viktor',
    zone: 'rocky_canyon',
    x: 3950,
    y: 950,
    spawnX: 3950,
    spawnY: 950,
    maxHp: 1400,
    hp: 1400,
    atk: 42,
    def: 20,
    speed: 2.2,
    expReward: 700,
    goldReward: 800,
    isBoss: true,
    isHumanoid: true,
    weaponType: 'ak47',
    humanChibi: {
      hairStyle: 'spiky',
      hairColor: '#EF4444',
      earType: 'none',
      earColor: '#991B1B',
      haloType: 'cross',
      haloColor: '#DC2626',
      coatColor: '#0F172A',
      skirtColor: '#7F1D1D',
      eyeType: 'determined',
      ribbonColor: '#EF4444',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_ak47', chance: 0.75, minQty: 1, maxQty: 1 },
      { itemId: 'wpn_bandit_revolver', chance: 0.6, minQty: 1, maxQty: 1 },
      { itemId: 'head_outlaw_stetson', chance: 0.5, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_l', chance: 1.0, minQty: 2, maxQty: 3 },
      { itemId: 'mat_outlaw_badge', chance: 1.0, minQty: 5, maxQty: 8 },
    ],
    animTimer: 0,
  },

  // MAIN WORLD BOSS: "Iron Mask" Sledge (The Welder Boss with Giant Sledgehammer)
  {
    id: 'boss_welder',
    name: '"Iron Mask" Sledge (The Welder)',
    type: 'boss_welder',
    zone: 'welder_crag',
    x: 3650,
    y: 2350,
    spawnX: 3650,
    spawnY: 2350,
    maxHp: 2800,
    hp: 2800,
    atk: 58,
    def: 32,
    speed: 1.6,
    expReward: 1800,
    goldReward: 2500,
    isBoss: true,
    isHumanoid: true,
    weaponType: 'sledgehammer',
    humanChibi: {
      hairStyle: 'short_messy',
      hairColor: '#1F2937',
      earType: 'none',
      earColor: '#111827',
      haloType: 'crown',
      haloColor: '#F59E0B',
      coatColor: '#1C1917',
      skirtColor: '#44403C',
      eyeType: 'determined',
      ribbonColor: '#EA580C',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_welder_sledge', chance: 0.85, minQty: 1, maxQty: 1 },
      { itemId: 'head_welder_mask', chance: 0.75, minQty: 1, maxQty: 1 },
      { itemId: 'wpn_cheytac', chance: 0.5, minQty: 1, maxQty: 1 },
      { itemId: 'mat_welder_scrap', chance: 1.0, minQty: 4, maxQty: 6 },
      { itemId: 'item_ramen_bowl', chance: 1.0, minQty: 3, maxQty: 5 },
    ],
    animTimer: 0,
  },

  // =========================================================
  // FACTION 1: POLICE SWAT PRECINCT (LEFT WARZONE & FRONTLINE)
  // =========================================================
  // 1. SWAT Shield Enforcers (Ballistic Shield + Stun Baton - Blocks Frontal Bullets)
  {
    id: 'cop_shield_1',
    name: 'SWAT Shield Enforcer',
    type: 'cop_officer',
    zone: 'cop_precinct',
    faction: 'police',
    x: 2000,
    y: 3450,
    spawnX: 2000,
    spawnY: 3450,
    maxHp: 320,
    hp: 320,
    atk: 24,
    def: 22,
    speed: 2.1,
    expReward: 110,
    goldReward: 95,
    isHumanoid: true,
    hasShield: true,
    shieldHp: 300,
    weaponType: 'baton',
    humanChibi: {
      hairStyle: 'short_messy',
      hairColor: '#0F172A',
      earType: 'none',
      earColor: '#0284C7',
      haloType: 'cyber_hex',
      haloColor: '#38BDF8',
      coatColor: '#1E3A8A',
      skirtColor: '#0F172A',
      eyeType: 'determined',
      ribbonColor: '#38BDF8',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_pistol', chance: 0.5, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_s', chance: 0.8, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'cop_shield_2',
    name: 'SWAT Shield Enforcer',
    type: 'cop_officer',
    zone: 'warzone_frontline',
    faction: 'police',
    x: 2250,
    y: 3750,
    spawnX: 2250,
    spawnY: 3750,
    maxHp: 320,
    hp: 320,
    atk: 24,
    def: 22,
    speed: 2.1,
    expReward: 110,
    goldReward: 95,
    isHumanoid: true,
    hasShield: true,
    shieldHp: 300,
    weaponType: 'baton',
    humanChibi: {
      hairStyle: 'bob',
      hairColor: '#1E293B',
      earType: 'none',
      earColor: '#0284C7',
      haloType: 'circle',
      haloColor: '#0284C7',
      coatColor: '#1E40AF',
      skirtColor: '#09090B',
      eyeType: 'determined',
      ribbonColor: '#60A5FA',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_pistol', chance: 0.5, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_s', chance: 0.8, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'cop_shield_3',
    name: 'SWAT Shield Enforcer',
    type: 'cop_officer',
    zone: 'warzone_frontline',
    faction: 'police',
    x: 2300,
    y: 3550,
    spawnX: 2300,
    spawnY: 3550,
    maxHp: 320,
    hp: 320,
    atk: 24,
    def: 22,
    speed: 2.1,
    expReward: 110,
    goldReward: 95,
    isHumanoid: true,
    hasShield: true,
    shieldHp: 300,
    weaponType: 'baton',
    humanChibi: {
      hairStyle: 'spiky',
      hairColor: '#0F172A',
      earType: 'cyber_antennas',
      earColor: '#38BDF8',
      haloType: 'cyber_hex',
      haloColor: '#38BDF8',
      coatColor: '#1E3A8A',
      skirtColor: '#0F172A',
      eyeType: 'determined',
      ribbonColor: '#38BDF8',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_pistol', chance: 0.5, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_s', chance: 0.8, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },

  // 2. SWAT Tactical Officers & Brawlers (Nightstick / Pistol)
  {
    id: 'cop_patrol_1',
    name: 'Precinct Officer (Nightstick)',
    type: 'cop_officer',
    zone: 'cop_precinct',
    faction: 'police',
    x: 1800,
    y: 3450,
    spawnX: 1800,
    spawnY: 3450,
    maxHp: 240,
    hp: 240,
    atk: 22,
    def: 12,
    speed: 2.4,
    expReward: 90,
    goldReward: 80,
    isHumanoid: true,
    weaponType: 'baton',
    humanChibi: {
      hairStyle: 'short_messy',
      hairColor: '#0F172A',
      earType: 'none',
      earColor: '#0284C7',
      haloType: 'circle',
      haloColor: '#38BDF8',
      coatColor: '#1E3A8A',
      skirtColor: '#172554',
      eyeType: 'determined',
      ribbonColor: '#38BDF8',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_pistol', chance: 0.5, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_s', chance: 0.8, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'cop_patrol_2',
    name: 'Police Enforcer (9mm Pistol)',
    type: 'cop_officer',
    zone: 'cop_precinct',
    faction: 'police',
    x: 1950,
    y: 3600,
    spawnX: 1950,
    spawnY: 3600,
    maxHp: 220,
    hp: 220,
    atk: 24,
    def: 10,
    speed: 2.5,
    expReward: 95,
    goldReward: 85,
    isHumanoid: true,
    weaponType: 'pistol',
    humanChibi: {
      hairStyle: 'bob',
      hairColor: '#334155',
      earType: 'none',
      earColor: '#0284C7',
      haloType: 'cyber_hex',
      haloColor: '#0284C7',
      coatColor: '#1E40AF',
      skirtColor: '#0F172A',
      eyeType: 'determined',
      ribbonColor: '#60A5FA',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_pistol', chance: 0.6, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_s', chance: 0.7, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'cop_patrol_3',
    name: 'Police Rapid Enforcer (9mm Pistol)',
    type: 'cop_officer',
    zone: 'warzone_frontline',
    faction: 'police',
    x: 2150,
    y: 3350,
    spawnX: 2150,
    spawnY: 3350,
    maxHp: 230,
    hp: 230,
    atk: 24,
    def: 11,
    speed: 2.6,
    expReward: 95,
    goldReward: 85,
    isHumanoid: true,
    weaponType: 'pistol',
    humanChibi: {
      hairStyle: 'wolf_cut',
      hairColor: '#1E3A8A',
      earType: 'none',
      earColor: '#38BDF8',
      haloType: 'star',
      haloColor: '#38BDF8',
      coatColor: '#172554',
      skirtColor: '#0F172A',
      eyeType: 'determined',
      ribbonColor: '#38BDF8',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_pistol', chance: 0.6, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_s', chance: 0.7, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'cop_patrol_4',
    name: 'Precinct Officer (Nightstick)',
    type: 'cop_officer',
    zone: 'warzone_frontline',
    faction: 'police',
    x: 2200,
    y: 3950,
    spawnX: 2200,
    spawnY: 3950,
    maxHp: 240,
    hp: 240,
    atk: 22,
    def: 12,
    speed: 2.5,
    expReward: 90,
    goldReward: 80,
    isHumanoid: true,
    weaponType: 'baton',
    humanChibi: {
      hairStyle: 'spiky',
      hairColor: '#38BDF8',
      earType: 'none',
      earColor: '#0284C7',
      haloType: 'circle',
      haloColor: '#38BDF8',
      coatColor: '#1E3A8A',
      skirtColor: '#0F172A',
      eyeType: 'determined',
      ribbonColor: '#38BDF8',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_pistol', chance: 0.5, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_s', chance: 0.8, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },

  // 3. SWAT Breachers & Shotgunners (Heavy Close-Quarters Punch)
  {
    id: 'cop_swat_1',
    name: 'SWAT Vanguard (Assault Shotgun)',
    type: 'cop_swat',
    zone: 'cop_precinct',
    faction: 'police',
    x: 2050,
    y: 3750,
    spawnX: 2050,
    spawnY: 3750,
    maxHp: 380,
    hp: 380,
    atk: 32,
    def: 18,
    speed: 2.1,
    expReward: 160,
    goldReward: 150,
    isHumanoid: true,
    weaponType: 'shotgun',
    humanChibi: {
      hairStyle: 'spiky',
      hairColor: '#1E293B',
      earType: 'none',
      earColor: '#0284C7',
      haloType: 'star',
      haloColor: '#38BDF8',
      coatColor: '#0F172A',
      skirtColor: '#09090B',
      eyeType: 'determined',
      ribbonColor: '#3B82F6',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_shotgun', chance: 0.45, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_l', chance: 0.6, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'cop_swat_2',
    name: 'SWAT Heavy Breacher (Assault Shotgun)',
    type: 'cop_swat',
    zone: 'warzone_frontline',
    faction: 'police',
    x: 2350,
    y: 3600,
    spawnX: 2350,
    spawnY: 3600,
    maxHp: 380,
    hp: 380,
    atk: 32,
    def: 18,
    speed: 2.1,
    expReward: 160,
    goldReward: 150,
    isHumanoid: true,
    weaponType: 'shotgun',
    humanChibi: {
      hairStyle: 'short_messy',
      hairColor: '#0284C7',
      earType: 'none',
      earColor: '#0369A1',
      haloType: 'crown',
      haloColor: '#38BDF8',
      coatColor: '#0F172A',
      skirtColor: '#1E3A8A',
      eyeType: 'determined',
      ribbonColor: '#60A5FA',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_shotgun', chance: 0.45, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_l', chance: 0.6, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'cop_swat_3',
    name: 'SWAT Heavy Breacher (Assault Shotgun)',
    type: 'cop_swat',
    zone: 'warzone_frontline',
    faction: 'police',
    x: 2400,
    y: 4100,
    spawnX: 2400,
    spawnY: 4100,
    maxHp: 380,
    hp: 380,
    atk: 32,
    def: 18,
    speed: 2.1,
    expReward: 160,
    goldReward: 150,
    isHumanoid: true,
    weaponType: 'shotgun',
    humanChibi: {
      hairStyle: 'wolf_cut',
      hairColor: '#334155',
      earType: 'none',
      earColor: '#0284C7',
      haloType: 'star',
      haloColor: '#38BDF8',
      coatColor: '#1E293B',
      skirtColor: '#0F172A',
      eyeType: 'determined',
      ribbonColor: '#38BDF8',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_shotgun', chance: 0.45, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_l', chance: 0.6, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },

  // 4. SWAT Commandos & SMG Slide Gunners (MAC-10 / AK-47)
  {
    id: 'cop_commando_1',
    name: 'SWAT Commando (MAC-10 SMG)',
    type: 'cop_officer',
    zone: 'warzone_frontline',
    faction: 'police',
    x: 2200,
    y: 3500,
    spawnX: 2200,
    spawnY: 3500,
    maxHp: 290,
    hp: 290,
    atk: 28,
    def: 14,
    speed: 2.7,
    expReward: 140,
    goldReward: 130,
    isHumanoid: true,
    weaponType: 'mac10',
    humanChibi: {
      hairStyle: 'spiky',
      hairColor: '#38BDF8',
      earType: 'none',
      earColor: '#0284C7',
      haloType: 'star',
      haloColor: '#38BDF8',
      coatColor: '#0F172A',
      skirtColor: '#1E40AF',
      eyeType: 'determined',
      ribbonColor: '#60A5FA',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_mac10', chance: 0.5, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_s', chance: 0.7, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'cop_commando_2',
    name: 'SWAT Assault Commando (AK-47 Rifle)',
    type: 'cop_officer',
    zone: 'warzone_frontline',
    faction: 'police',
    x: 2100,
    y: 3850,
    spawnX: 2100,
    spawnY: 3850,
    maxHp: 310,
    hp: 310,
    atk: 32,
    def: 15,
    speed: 2.5,
    expReward: 160,
    goldReward: 150,
    isHumanoid: true,
    weaponType: 'ak47',
    humanChibi: {
      hairStyle: 'short_messy',
      hairColor: '#0284C7',
      earType: 'none',
      earColor: '#0369A1',
      haloType: 'cyber_hex',
      haloColor: '#38BDF8',
      coatColor: '#0F172A',
      skirtColor: '#172554',
      eyeType: 'determined',
      ribbonColor: '#38BDF8',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_ak47', chance: 0.45, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_l', chance: 0.6, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },

  // 5. SWAT Elite Snipers
  {
    id: 'cop_marksman_1',
    name: 'SWAT Overwatch (CheyTac Sniper)',
    type: 'cop_marksman',
    zone: 'cop_precinct',
    faction: 'police',
    x: 1650,
    y: 3350,
    spawnX: 1650,
    spawnY: 3350,
    maxHp: 260,
    hp: 260,
    atk: 40,
    def: 12,
    speed: 2.0,
    expReward: 180,
    goldReward: 160,
    isHumanoid: true,
    weaponType: 'cheytac',
    humanChibi: {
      hairStyle: 'wolf_cut',
      hairColor: '#0284C7',
      earType: 'none',
      earColor: '#0369A1',
      haloType: 'star',
      haloColor: '#0EA5E9',
      coatColor: '#0F172A',
      skirtColor: '#1E3A8A',
      eyeType: 'determined',
      ribbonColor: '#38BDF8',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_cheytac', chance: 0.35, minQty: 1, maxQty: 1 },
    ],
    animTimer: 0,
  },
  {
    id: 'cop_marksman_2',
    name: 'SWAT Long-Range Sniper',
    type: 'cop_marksman',
    zone: 'cop_precinct',
    faction: 'police',
    x: 1750,
    y: 4150,
    spawnX: 1750,
    spawnY: 4150,
    maxHp: 260,
    hp: 260,
    atk: 40,
    def: 12,
    speed: 2.0,
    expReward: 180,
    goldReward: 160,
    isHumanoid: true,
    weaponType: 'cheytac',
    humanChibi: {
      hairStyle: 'braids',
      hairColor: '#38BDF8',
      earType: 'none',
      earColor: '#0284C7',
      haloType: 'star',
      haloColor: '#38BDF8',
      coatColor: '#0F172A',
      skirtColor: '#1E3A8A',
      eyeType: 'determined',
      ribbonColor: '#38BDF8',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_cheytac', chance: 0.35, minQty: 1, maxQty: 1 },
    ],
    animTimer: 0,
  },

  // 6. POLICE JUGGERNAUTS (Titan Tanks)
  {
    id: 'cop_juggernaut_1',
    name: 'SWAT Juggernaut "Titan Bulwark"',
    type: 'cop_juggernaut',
    zone: 'cop_precinct',
    faction: 'police',
    isJuggernaut: true,
    isBoss: true,
    x: 1900,
    y: 3550,
    spawnX: 1900,
    spawnY: 3550,
    maxHp: 2400,
    hp: 2400,
    atk: 48,
    def: 35,
    speed: 1.6,
    expReward: 1400,
    goldReward: 1800,
    isHumanoid: true,
    weaponType: 'sledgehammer',
    humanChibi: {
      hairStyle: 'short_messy',
      hairColor: '#0284C7',
      earType: 'cyber_antennas',
      earColor: '#38BDF8',
      haloType: 'crown',
      haloColor: '#38BDF8',
      coatColor: '#0369A1',
      skirtColor: '#082F49',
      eyeType: 'determined',
      ribbonColor: '#0284C7',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_shotgun', chance: 0.8, minQty: 1, maxQty: 1 },
      { itemId: 'wpn_cheytac', chance: 0.5, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_l', chance: 1.0, minQty: 2, maxQty: 4 },
    ],
    animTimer: 0,
  },
  {
    id: 'cop_juggernaut_2',
    name: 'SWAT Titan "Ironclad Vanguard"',
    type: 'cop_juggernaut',
    zone: 'warzone_frontline',
    faction: 'police',
    isJuggernaut: true,
    isBoss: true,
    x: 2200,
    y: 3750,
    spawnX: 2200,
    spawnY: 3750,
    maxHp: 2600,
    hp: 2600,
    atk: 50,
    def: 38,
    speed: 1.5,
    expReward: 1500,
    goldReward: 1900,
    isHumanoid: true,
    weaponType: 'shotgun',
    humanChibi: {
      hairStyle: 'spiky',
      hairColor: '#1E293B',
      earType: 'cyber_antennas',
      earColor: '#0284C7',
      haloType: 'crown',
      haloColor: '#38BDF8',
      coatColor: '#0F172A',
      skirtColor: '#0369A1',
      eyeType: 'determined',
      ribbonColor: '#38BDF8',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_shotgun', chance: 0.9, minQty: 1, maxQty: 1 },
      { itemId: 'wpn_ak47', chance: 0.6, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_l', chance: 1.0, minQty: 3, maxQty: 5 },
    ],
    animTimer: 0,
  },

  // =========================================================
  // FACTION 2: DEMON PUNK SYNDICATE (RIGHT WARZONE & FRONTLINE)
  // =========================================================
  // 1. Punk Anarchists (Spiked Bat Rushdown & Acrobat Jumpers)
  {
    id: 'punk_anarchist_1',
    name: 'Punk Anarchist (Spiked Bat)',
    type: 'punk_grunt',
    zone: 'punk_territory',
    faction: 'punk_demon',
    x: 3200,
    y: 3450,
    spawnX: 3200,
    spawnY: 3450,
    maxHp: 250,
    hp: 250,
    atk: 26,
    def: 10,
    speed: 2.6,
    expReward: 95,
    goldReward: 85,
    isHumanoid: true,
    weaponType: 'bat',
    humanChibi: {
      hairStyle: 'spiky',
      hairColor: '#F43F5E',
      earType: 'horns',
      earColor: '#BE123C',
      haloType: 'cross',
      haloColor: '#E11D48',
      coatColor: '#18181B',
      skirtColor: '#881337',
      eyeType: 'determined',
      ribbonColor: '#F43F5E',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_mac10', chance: 0.4, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_s', chance: 0.8, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'punk_anarchist_2',
    name: 'Punk Berserker (Spiked Bat)',
    type: 'punk_grunt',
    zone: 'warzone_frontline',
    faction: 'punk_demon',
    x: 2750,
    y: 3600,
    spawnX: 2750,
    spawnY: 3600,
    maxHp: 260,
    hp: 260,
    atk: 28,
    def: 10,
    speed: 2.7,
    expReward: 100,
    goldReward: 90,
    isHumanoid: true,
    weaponType: 'bat',
    humanChibi: {
      hairStyle: 'wolf_cut',
      hairColor: '#EF4444',
      earType: 'horns',
      earColor: '#991B1B',
      haloType: 'crown',
      haloColor: '#F87171',
      coatColor: '#27272A',
      skirtColor: '#7F1D1D',
      eyeType: 'determined',
      ribbonColor: '#EF4444',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_mac10', chance: 0.4, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_s', chance: 0.8, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'punk_anarchist_3',
    name: 'Demon Rusher (Spiked Bat)',
    type: 'punk_grunt',
    zone: 'warzone_frontline',
    faction: 'punk_demon',
    x: 2700,
    y: 3800,
    spawnX: 2700,
    spawnY: 3800,
    maxHp: 250,
    hp: 250,
    atk: 26,
    def: 10,
    speed: 2.6,
    expReward: 95,
    goldReward: 85,
    isHumanoid: true,
    weaponType: 'bat',
    humanChibi: {
      hairStyle: 'spiky',
      hairColor: '#DC2626',
      earType: 'horns',
      earColor: '#7F1D1D',
      haloType: 'cross',
      haloColor: '#EF4444',
      coatColor: '#09090B',
      skirtColor: '#450A0A',
      eyeType: 'determined',
      ribbonColor: '#DC2626',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_mac10', chance: 0.4, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_s', chance: 0.8, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'punk_anarchist_4',
    name: 'Demon Blade Dancer (Trench Blade)',
    type: 'punk_grunt',
    zone: 'warzone_frontline',
    faction: 'punk_demon',
    x: 2850,
    y: 3400,
    spawnX: 2850,
    spawnY: 3400,
    maxHp: 270,
    hp: 270,
    atk: 30,
    def: 12,
    speed: 2.8,
    expReward: 120,
    goldReward: 110,
    isHumanoid: true,
    weaponType: 'blade',
    humanChibi: {
      hairStyle: 'long_flowing',
      hairColor: '#E11D48',
      earType: 'horns',
      earColor: '#9F1239',
      haloType: 'cross',
      haloColor: '#FB7185',
      coatColor: '#18181B',
      skirtColor: '#881337',
      eyeType: 'determined',
      ribbonColor: '#F43F5E',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_neon_katana', chance: 0.4, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_s', chance: 0.8, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },

  // 2. Hellfire Pyros (Molotov Cocktails - Burning Fire Pools)
  {
    id: 'punk_molotov_1',
    name: 'Hellfire Pyro (Molotov Cocktail)',
    type: 'punk_molotov',
    zone: 'punk_territory',
    faction: 'punk_demon',
    x: 3100,
    y: 3650,
    spawnX: 3100,
    spawnY: 3650,
    maxHp: 230,
    hp: 230,
    atk: 30,
    def: 8,
    speed: 2.3,
    expReward: 120,
    goldReward: 110,
    isHumanoid: true,
    weaponType: 'molotov',
    humanChibi: {
      hairStyle: 'cyber_buns',
      hairColor: '#FB923C',
      earType: 'horns',
      earColor: '#C2410C',
      haloType: 'floral',
      haloColor: '#EA580C',
      coatColor: '#27272A',
      skirtColor: '#7C2D12',
      eyeType: 'smug',
      ribbonColor: '#F97316',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_mac10', chance: 0.5, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_s', chance: 0.8, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'punk_molotov_2',
    name: 'Hellfire Pyro Maniac (Molotov Cocktail)',
    type: 'punk_molotov',
    zone: 'warzone_frontline',
    faction: 'punk_demon',
    x: 2800,
    y: 3750,
    spawnX: 2800,
    spawnY: 3750,
    maxHp: 230,
    hp: 230,
    atk: 32,
    def: 8,
    speed: 2.3,
    expReward: 120,
    goldReward: 110,
    isHumanoid: true,
    weaponType: 'molotov',
    humanChibi: {
      hairStyle: 'spiky',
      hairColor: '#EA580C',
      earType: 'horns',
      earColor: '#9A3412',
      haloType: 'floral',
      haloColor: '#F97316',
      coatColor: '#18181B',
      skirtColor: '#C2410C',
      eyeType: 'determined',
      ribbonColor: '#EA580C',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_mac10', chance: 0.5, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_s', chance: 0.8, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'punk_molotov_3',
    name: 'Hellfire Pyro Maniac (Molotov Cocktail)',
    type: 'punk_molotov',
    zone: 'warzone_frontline',
    faction: 'punk_demon',
    x: 2900,
    y: 4050,
    spawnX: 2900,
    spawnY: 4050,
    maxHp: 230,
    hp: 230,
    atk: 32,
    def: 8,
    speed: 2.3,
    expReward: 120,
    goldReward: 110,
    isHumanoid: true,
    weaponType: 'molotov',
    humanChibi: {
      hairStyle: 'twintails',
      hairColor: '#F97316',
      earType: 'horns',
      earColor: '#C2410C',
      haloType: 'cross',
      haloColor: '#FB923C',
      coatColor: '#27272A',
      skirtColor: '#7C2D12',
      eyeType: 'smug',
      ribbonColor: '#F97316',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_mac10', chance: 0.5, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_s', chance: 0.8, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },

  // 3. Punk Dual Gunner & MAC-10 Lead Sprayers
  {
    id: 'punk_gunner_1',
    name: 'Demon Outlaw (MAC-10 SMG)',
    type: 'punk_anarchist',
    zone: 'punk_territory',
    faction: 'punk_demon',
    x: 3350,
    y: 3750,
    spawnX: 3350,
    spawnY: 3750,
    maxHp: 270,
    hp: 270,
    atk: 28,
    def: 12,
    speed: 2.5,
    expReward: 150,
    goldReward: 140,
    isHumanoid: true,
    weaponType: 'mac10',
    humanChibi: {
      hairStyle: 'wolf_cut',
      hairColor: '#A855F7',
      earType: 'horns',
      earColor: '#7E22CE',
      haloType: 'cross',
      haloColor: '#C084FC',
      coatColor: '#18181B',
      skirtColor: '#581C87',
      eyeType: 'determined',
      ribbonColor: '#A855F7',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_mac10', chance: 0.6, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_l', chance: 0.6, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'punk_gunner_2',
    name: 'Demon Lead Sprayer (Dual MAC-10)',
    type: 'punk_anarchist',
    zone: 'warzone_frontline',
    faction: 'punk_demon',
    x: 2750,
    y: 3450,
    spawnX: 2750,
    spawnY: 3450,
    maxHp: 280,
    hp: 280,
    atk: 28,
    def: 12,
    speed: 2.7,
    expReward: 150,
    goldReward: 140,
    isHumanoid: true,
    weaponType: 'mac10',
    humanChibi: {
      hairStyle: 'spiky',
      hairColor: '#C084FC',
      earType: 'horns',
      earColor: '#9333EA',
      haloType: 'cross',
      haloColor: '#E879F9',
      coatColor: '#09090B',
      skirtColor: '#6B21A8',
      eyeType: 'determined',
      ribbonColor: '#A855F7',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_mac10', chance: 0.6, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_l', chance: 0.6, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'punk_gunner_3',
    name: 'Demon Lead Sprayer (Dual MAC-10)',
    type: 'punk_anarchist',
    zone: 'warzone_frontline',
    faction: 'punk_demon',
    x: 2850,
    y: 3900,
    spawnX: 2850,
    spawnY: 3900,
    maxHp: 280,
    hp: 280,
    atk: 28,
    def: 12,
    speed: 2.7,
    expReward: 150,
    goldReward: 140,
    isHumanoid: true,
    weaponType: 'mac10',
    humanChibi: {
      hairStyle: 'braids',
      hairColor: '#F43F5E',
      earType: 'horns',
      earColor: '#BE123C',
      haloType: 'star',
      haloColor: '#FB7185',
      coatColor: '#18181B',
      skirtColor: '#881337',
      eyeType: 'determined',
      ribbonColor: '#F43F5E',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_mac10', chance: 0.6, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_l', chance: 0.6, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },

  // 4. Punk Shotgunners & AK-47 Rebels
  {
    id: 'punk_shotgun_1',
    name: 'Punk Slugger (Sawed-Off Shotgun)',
    type: 'bandit_shotgunner',
    zone: 'warzone_frontline',
    faction: 'punk_demon',
    x: 2650,
    y: 3550,
    spawnX: 2650,
    spawnY: 3550,
    maxHp: 360,
    hp: 360,
    atk: 34,
    def: 16,
    speed: 2.2,
    expReward: 160,
    goldReward: 150,
    isHumanoid: true,
    weaponType: 'shotgun',
    humanChibi: {
      hairStyle: 'spiky',
      hairColor: '#EA580C',
      earType: 'horns',
      earColor: '#9A3412',
      haloType: 'cross',
      haloColor: '#F97316',
      coatColor: '#18181B',
      skirtColor: '#7C2D12',
      eyeType: 'determined',
      ribbonColor: '#EA580C',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_shotgun', chance: 0.5, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_l', chance: 0.6, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'punk_rebel_1',
    name: 'Demon Anarchist Rebel (AK-47)',
    type: 'punk_anarchist',
    zone: 'warzone_frontline',
    faction: 'punk_demon',
    x: 2750,
    y: 3700,
    spawnX: 2750,
    spawnY: 3700,
    maxHp: 320,
    hp: 320,
    atk: 32,
    def: 14,
    speed: 2.5,
    expReward: 160,
    goldReward: 150,
    isHumanoid: true,
    weaponType: 'ak47',
    humanChibi: {
      hairStyle: 'wolf_cut',
      hairColor: '#DC2626',
      earType: 'horns',
      earColor: '#991B1B',
      haloType: 'crown',
      haloColor: '#EF4444',
      coatColor: '#09090B',
      skirtColor: '#450A0A',
      eyeType: 'determined',
      ribbonColor: '#DC2626',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_ak47', chance: 0.5, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_l', chance: 0.6, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },

  // 5. DEMON PUNK JUGGERNAUTS & OVERLORDS
  {
    id: 'punk_juggernaut_1',
    name: 'Demon Overlord "Hellfire Jax"',
    type: 'punk_juggernaut',
    zone: 'punk_territory',
    faction: 'punk_demon',
    isJuggernaut: true,
    isBoss: true,
    x: 3100,
    y: 3550,
    spawnX: 3100,
    spawnY: 3550,
    maxHp: 2600,
    hp: 2600,
    atk: 52,
    def: 30,
    speed: 1.7,
    expReward: 1500,
    goldReward: 2000,
    isHumanoid: true,
    weaponType: 'ak47',
    humanChibi: {
      hairStyle: 'spiky',
      hairColor: '#DC2626',
      earType: 'horns',
      earColor: '#991B1B',
      haloType: 'crown',
      haloColor: '#EF4444',
      coatColor: '#09090B',
      skirtColor: '#450A0A',
      eyeType: 'determined',
      ribbonColor: '#DC2626',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_ak47', chance: 0.85, minQty: 1, maxQty: 1 },
      { itemId: 'wpn_bandit_revolver', chance: 0.7, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_l', chance: 1.0, minQty: 2, maxQty: 4 },
    ],
    animTimer: 0,
  },
  {
    id: 'punk_juggernaut_2',
    name: 'Demon Warlord "Crimson Slaughterer"',
    type: 'punk_juggernaut',
    zone: 'warzone_frontline',
    faction: 'punk_demon',
    isJuggernaut: true,
    isBoss: true,
    x: 2800,
    y: 3850,
    spawnX: 2800,
    spawnY: 3850,
    maxHp: 2800,
    hp: 2800,
    atk: 56,
    def: 34,
    speed: 1.6,
    expReward: 1600,
    goldReward: 2100,
    isHumanoid: true,
    weaponType: 'sledgehammer',
    humanChibi: {
      hairStyle: 'wolf_cut',
      hairColor: '#991B1B',
      earType: 'horns',
      earColor: '#450A0A',
      haloType: 'crown',
      haloColor: '#EF4444',
      coatColor: '#18181B',
      skirtColor: '#7F1D1D',
      eyeType: 'determined',
      ribbonColor: '#DC2626',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_welder_sledge', chance: 0.85, minQty: 1, maxQty: 1 },
      { itemId: 'wpn_ak47', chance: 0.75, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_l', chance: 1.0, minQty: 3, maxQty: 5 },
    ],
    animTimer: 0,
  },
];

export const CLASS_DEFAULTS = {
  gunslinger: {
    name: 'Outlaw Gunslinger',
    desc: 'High-velocity firearm specialist with rapid bullet stream, fan spread, and aerial ricochet.',
    baseHp: 320,
    baseMp: 100,
    baseAtk: 24,
    baseDef: 14,
    baseSpd: 4.8,
    starterWeapon: 'wpn_starter_pistol',
    starterSkills: [
      {
        id: 'skill_gatling_burst',
        name: 'Rapid Fire Burst',
        icon: '⚡',
        description: 'Fires an automatic rapid-fire stream of 12 high-velocity bullets toward your cursor.',
        costMp: 0,
        cooldown: 2.2,
        lastUsed: 0,
        unlockLevel: 1,
        level: 1,
        maxLevel: 5,
        type: 'damage' as const,
        damageMult: 2.5,
        range: 1200,
      },
      {
        id: 'skill_bullet_fan',
        name: 'Fan of Bullets (Spread)',
        icon: '💥',
        description: 'Unleashes a wide 9-bullet penetrating spread in a 75-degree frontal cone.',
        costMp: 0,
        cooldown: 3.2,
        lastUsed: 0,
        unlockLevel: 2,
        level: 1,
        maxLevel: 5,
        type: 'aoe' as const,
        damageMult: 2.8,
        range: 1100,
      },
      {
        id: 'skill_aerial_aimbot',
        name: 'Aerial Aimbot & Ricochet',
        icon: '🎯',
        description: 'Vaults high into the air with aimbot laser locks, raining down homing bullets that ricochet between targets!',
        costMp: 0,
        cooldown: 7.0,
        lastUsed: 0,
        unlockLevel: 3,
        level: 1,
        maxLevel: 5,
        type: 'ultimate' as const,
        damageMult: 4.8,
        range: 1400,
      },
    ],
  },
  swordmaster: {
    name: 'Survival Blade Fighter',
    desc: 'Melee fighter with throwing knives, katana, scythe, and a colossal zweihander.',
    baseHp: 400,
    baseMp: 80,
    baseAtk: 30,
    baseDef: 20,
    baseSpd: 4.5,
    starterWeapon: 'wpn_neon_katana',
    starterSkills: [
      {
        id: 'skill_spinning_blade',
        name: 'Skyward Slam',
        icon: '☄️',
        description: 'Leap high into the air towards the cursor, then slam down creating expanding shockwave circles that damage and knock back all enemies.',
        costMp: 0,
        cooldown: 3.5,
        lastUsed: 0,
        unlockLevel: 1,
        level: 1,
        maxLevel: 5,
        type: 'damage' as const,
        damageMult: 3.5,
        range: 500,
      },
      {
        id: 'skill_slash_scatter',
        name: 'Shadow Slash Dash',
        icon: '💨',
        description: 'Dash forward in a flash, slashing all enemies in your way, and then dash back to your original position.',
        costMp: 0,
        cooldown: 4.8,
        lastUsed: 0,
        unlockLevel: 2,
        level: 1,
        maxLevel: 5,
        type: 'aoe' as const,
        damageMult: 2.2,
        range: 320,
      },
      {
        id: 'skill_blade_storm',
        name: 'Omnislash Flurry',
        icon: '⚔️',
        description: 'Unleash a flurry of 12 rapid teleportation strikes on enemies near the cursor, dealing massive critical damage, ending with a giant sword rain.',
        costMp: 0,
        cooldown: 9.0,
        lastUsed: 0,
        unlockLevel: 3,
        level: 1,
        maxLevel: 5,
        type: 'ultimate' as const,
        damageMult: 6.5,
        range: 400,
      },
    ],
  },
  cybermage: {
    name: 'Hellfire Mage',
    desc: 'Caster of fireballs, particles, cosmic singularities, cascading lightning, and glacial paths.',
    baseHp: 290,
    baseMp: 140,
    baseAtk: 26,
    baseDef: 12,
    baseSpd: 4.6,
    starterWeapon: 'wpn_arcane_staff',
    starterSkills: [
      {
        id: 'skill_meteor_rain',
        name: 'Meteor Cataclysm',
        icon: '☄️',
        description: 'Triggers a devastating meteor shower followed by a colossal central impact.',
        costMp: 0,
        cooldown: 4.5,
        lastUsed: 0,
        unlockLevel: 1,
        level: 1,
        maxLevel: 5,
        type: 'aoe' as const,
        damageMult: 2.6,
        range: 900,
      },
      {
        id: 'skill_hellhounds',
        name: 'Storm Call',
        icon: '⚡',
        description: 'Summons thunder and lightning from the sky, striking all nearby enemies with cascading lightning.',
        costMp: 0,
        cooldown: 8.0,
        lastUsed: 0,
        unlockLevel: 2,
        level: 1,
        maxLevel: 5,
        type: 'buff' as const,
        damageMult: 1.8,
        range: 700,
      },
      {
        id: 'skill_titan_golem',
        name: 'Glacial Slide',
        icon: '❄️',
        description: 'Dashes forward leaving a wide frozen trail that boosts movement speed for all players.',
        costMp: 0,
        cooldown: 12.0,
        lastUsed: 0,
        unlockLevel: 3,
        level: 1,
        maxLevel: 5,
        type: 'ultimate' as const,
        damageMult: 6.0,
        range: 450,
      },
    ],
  },
};

export const CLASS_HOTBAR: Record<CharacterClass, GunType[]> = {
  gunslinger: ['pistol', 'revolver', 'mac10', 'ak47', 'shotgun', 'cheytac'],
  swordmaster: ['throwing_knives', 'katana', 'scythe', 'greatsword'],
  cybermage: ['staff', 'wand', 'grimoire', 'totem'],
};

export const AUTO_FIRE_GUNS: GunType[] = ['mac10', 'ak47', 'wand'];

export const AMMO_GUNS: GunType[] = ['pistol', 'revolver', 'mac10', 'ak47', 'shotgun', 'cheytac', 'throwing_knives'];
