import { Item, CraftRecipe, Quest, NPC, Monster, ResourceNode, Obstacle, InteractiveObject } from '../types/game';

export const WORLD_WIDTH = 5400;
export const WORLD_HEIGHT = 4400;

export const ZONES = [
  {
    id: 'forest_camp',
    name: 'Survivor Forest Campsite',
    bounds: { minX: 100, minY: 100, maxX: 1800, maxY: 1600 },
    bgTheme: 'camp',
    desc: 'Deep pine woods with expedition canvas tents, roaring campfire, supply crates, and friendly survivor NPCs.',
  },
  {
    id: 'deep_forest',
    name: 'Dense Emerald Pine Forest',
    bounds: { minX: 100, minY: 1600, maxX: 2600, maxY: 3100 },
    bgTheme: 'forest',
    desc: 'Dense ancient woods with harvestable timber, iron ore veins, crystal deposits, and feral wolves.',
  },
  {
    id: 'rocky_canyon',
    name: 'Jagged Foothills & Canyon Pass',
    bounds: { minX: 1800, minY: 100, maxX: 5300, maxY: 1600 },
    bgTheme: 'canyon',
    desc: 'Steep stone ravines and bandit encampments with explosive red barrels and outlaw sniper nests.',
  },
  {
    id: 'welder_crag',
    name: 'High Rock Summit & Welder Arena',
    bounds: { minX: 2600, minY: 1600, maxX: 5300, maxY: 3100 },
    bgTheme: 'mountain',
    desc: 'Towering cliff plateau guarded by the brutal hammer-wielding boss "Iron Mask" Sledge!',
  },
  {
    id: 'cop_precinct',
    name: 'SWAT Metro Precinct (Left Warzone)',
    bounds: { minX: 100, minY: 3100, maxX: 2400, maxY: 4300 },
    bgTheme: 'police',
    desc: 'Heavily fortified SWAT police sector with riot barriers, tactical officers, batons, and Titan Juggernauts.',
  },
  {
    id: 'punk_territory',
    name: 'Demon Punk Alley (Right Warzone)',
    bounds: { minX: 2800, minY: 3100, maxX: 5300, maxY: 4300 },
    bgTheme: 'punk',
    desc: 'Neon-lit gang turf of Punk Demons with spiked bats, MAC-10s, Molotov cocktails, and Hellfire Jax.',
  },
  {
    id: 'warzone_frontline',
    name: 'Street Frontline (No-Mans Land)',
    bounds: { minX: 2200, minY: 3100, maxX: 3000, maxY: 4300 },
    bgTheme: 'warzone',
    desc: 'Active clash line where Cops and Punks engage in constant warfare unless provoked by the player.',
  },
];

// SOLID OBSTACLES / INVISIBLE WALLS (Walkable vs Non-Walkable Collision Planes)
export const OBSTACLES: Obstacle[] = [
  // Forest Campsite Large Tents (Solid cloth & frame structures)
  { id: 'tent_main_hq', x: 580, y: 480, width: 140, height: 110, type: 'tent' },
  { id: 'tent_armory', x: 860, y: 480, width: 130, height: 100, type: 'tent' },
  { id: 'tent_kitchen', x: 420, y: 720, width: 120, height: 95, type: 'tent' },
  { id: 'tent_scout', x: 920, y: 740, width: 115, height: 90, type: 'tent' },
  
  // Campsite Campfire Pit (Solid stone ring)
  { id: 'campfire_pit_obs', x: 680, y: 640, width: 60, height: 60, shape: 'circle', radius: 32, type: 'campfire_base' },

  // Big Forest Boulders & Rock Formations
  { id: 'rock_forest_1', x: 260, y: 380, width: 80, height: 70, shape: 'circle', radius: 38, type: 'rock' },
  { id: 'rock_forest_2', x: 1250, y: 420, width: 100, height: 80, shape: 'circle', radius: 46, type: 'rock' },
  { id: 'rock_forest_3', x: 1520, y: 920, width: 110, height: 85, shape: 'circle', radius: 50, type: 'rock' },
  { id: 'rock_forest_4', x: 480, y: 1950, width: 90, height: 75, shape: 'circle', radius: 42, type: 'rock' },
  { id: 'rock_forest_5', x: 1450, y: 2450, width: 120, height: 95, shape: 'circle', radius: 55, type: 'rock' },

  // Mountain & Canyon Massive Cliffs (Impassable Rock Ridges / Walls)
  { id: 'cliff_canyon_north_1', x: 2400, y: 250, width: 450, height: 80, type: 'cliff' },
  { id: 'cliff_canyon_north_2', x: 3100, y: 280, width: 520, height: 85, type: 'cliff' },
  { id: 'cliff_canyon_mid_divider', x: 2850, y: 720, width: 80, height: 420, type: 'cliff' },
  { id: 'cliff_canyon_south_ridge', x: 3350, y: 1250, width: 620, height: 90, type: 'cliff' },

  // High Mountain Arena Plateau Walls & Summit Ridge
  { id: 'cliff_summit_wall_left', x: 2900, y: 1800, width: 90, height: 500, type: 'cliff' },
  { id: 'cliff_summit_wall_right', x: 4350, y: 1750, width: 90, height: 600, type: 'cliff' },
  { id: 'cliff_summit_wall_back', x: 3100, y: 2920, width: 1150, height: 95, type: 'cliff' },
  { id: 'boulder_arena_1', x: 3350, y: 2150, width: 90, height: 80, shape: 'circle', radius: 44, type: 'rock' },
  { id: 'boulder_arena_2', x: 4050, y: 2450, width: 95, height: 85, shape: 'circle', radius: 46, type: 'rock' },

  // Faction Warzone Obstacles (Police Barricades, Sandbags, Concrete Walls)
  { id: 'cop_barricade_1', x: 2100, y: 3400, width: 40, height: 180, type: 'wall' },
  { id: 'cop_barricade_2', x: 2100, y: 3800, width: 40, height: 200, type: 'wall' },
  { id: 'punk_barricade_1', x: 2900, y: 3400, width: 40, height: 180, type: 'wall' },
  { id: 'punk_barricade_2', x: 2900, y: 3800, width: 40, height: 200, type: 'wall' },
  { id: 'warzone_middle_bunker', x: 2450, y: 3600, width: 100, height: 80, type: 'wall' },
];

// INTERACTIVE OBJECTS (Explosive Barrels with high kinetic impact)
export const INITIAL_INTERACTIVE_OBJECTS: InteractiveObject[] = [
  // Campsite perimeter defense barrels
  { id: 'barrel_camp_1', type: 'explosive_barrel', x: 1150, y: 620, hp: 30, maxHp: 30, radius: 20 },
  { id: 'barrel_camp_2', type: 'explosive_barrel', x: 1220, y: 880, hp: 30, maxHp: 30, radius: 20 },

  // Canyon pass ambush barrels
  { id: 'barrel_canyon_1', type: 'explosive_barrel', x: 2250, y: 680, hp: 30, maxHp: 30, radius: 20 },
  { id: 'barrel_canyon_2', type: 'explosive_barrel', x: 2320, y: 650, hp: 30, maxHp: 30, radius: 20 },
  { id: 'barrel_canyon_3', type: 'explosive_barrel', x: 2750, y: 920, hp: 30, maxHp: 30, radius: 20 },
  { id: 'barrel_canyon_4', type: 'explosive_barrel', x: 3450, y: 850, hp: 30, maxHp: 30, radius: 20 },
  { id: 'barrel_canyon_5', type: 'explosive_barrel', x: 3520, y: 890, hp: 30, maxHp: 30, radius: 20 },
  { id: 'barrel_canyon_6', type: 'explosive_barrel', x: 3950, y: 650, hp: 30, maxHp: 30, radius: 20 },

  // Summit Arena combat barrels
  { id: 'barrel_arena_1', type: 'explosive_barrel', x: 3250, y: 2050, hp: 30, maxHp: 30, radius: 20 },
  { id: 'barrel_arena_2', type: 'explosive_barrel', x: 4150, y: 2150, hp: 30, maxHp: 30, radius: 20 },
  { id: 'barrel_arena_3', type: 'explosive_barrel', x: 3700, y: 2750, hp: 30, maxHp: 30, radius: 20 },
  { id: 'barrel_arena_4', type: 'explosive_barrel', x: 3780, y: 2780, hp: 30, maxHp: 30, radius: 20 },
];

export const ITEMS_DATABASE: Record<string, Item> = {
  // 1. Pistol (9mm Tactical Handgun / Starter)
  'wpn_starter_pistol': {
    id: 'wpn_starter_pistol',
    name: 'Tactical 9mm Pistol',
    type: 'weapon',
    gunType: 'pistol',
    rarity: 'common',
    icon: '🔫',
    description: 'Crisp semi-automatic 9mm handgun. Fast handling with pinpoint accuracy.',
    stats: { atk: 18, speed: 5, crit: 8 },
    price: 60,
  },
  'wpn_pistol': {
    id: 'wpn_pistol',
    name: 'P250 Combat Pistol',
    type: 'weapon',
    gunType: 'pistol',
    rarity: 'common',
    icon: '🔫',
    description: 'Standard issue military handgun. Reliable cadence and low recoil.',
    stats: { atk: 22, speed: 6, crit: 10 },
    price: 120,
  },

  // 2. Revolver (.44 Magnum Hand Cannon)
  'wpn_bandit_revolver': {
    id: 'wpn_bandit_revolver',
    name: '.44 Outlaw Heavy Revolver',
    type: 'weapon',
    gunType: 'revolver',
    rarity: 'rare',
    icon: '🔫',
    description: 'Massive caliber six-shooter. Thunderous blast with intense single-target impact and head knockback.',
    stats: { atk: 48, speed: 4, crit: 25 },
    price: 420,
  },
  'wpn_revolver': {
    id: 'wpn_revolver',
    name: 'Python .357 Revolver',
    type: 'weapon',
    gunType: 'revolver',
    rarity: 'rare',
    icon: '🔫',
    description: 'Polished steel magnum revolver with devastating stopping power.',
    stats: { atk: 44, speed: 5, crit: 22 },
    price: 380,
  },

  // 3. MAC-10 (Micro-SMG)
  'wpn_mac10': {
    id: 'wpn_mac10',
    name: 'MAC-10 Micro SMG',
    type: 'weapon',
    gunType: 'mac10',
    rarity: 'rare',
    icon: '💥',
    description: 'Extreme fire-rate compact submachine gun. Sprays a blistering cone of lead with flying brass.',
    stats: { atk: 17, speed: 12, crit: 12 },
    price: 550,
  },

  // 4. AK-47 (Kalash)
  'wpn_ak47': {
    id: 'wpn_ak47',
    name: 'AK-47 Kalashnikov',
    type: 'weapon',
    gunType: 'ak47',
    rarity: 'epic',
    icon: '🎯',
    description: 'Iconic assault rifle chambered in 7.62mm. High kinetic punch and superior combat range.',
    stats: { atk: 38, speed: 8, crit: 18 },
    price: 850,
  },

  // 5. Shotgun (Trench Sweeper Sawed-Off)
  'wpn_shotgun': {
    id: 'wpn_shotgun',
    name: 'Trench Sweeper Shotgun',
    type: 'weapon',
    gunType: 'shotgun',
    rarity: 'epic',
    icon: '🔥',
    description: 'Heavy 12-gauge pump shotgun. Blasts a wide 7-pellet spread that shreds close-range hostiles.',
    stats: { atk: 24, speed: 3, crit: 15 },
    price: 780,
  },

  // 6. CheyTac M200 (Intervention Sniper Rifle)
  'wpn_cheytac': {
    id: 'wpn_cheytac',
    name: 'CheyTac M200 Intervention',
    type: 'weapon',
    gunType: 'cheytac',
    rarity: 'legendary',
    icon: '⚡',
    description: 'Long-range .408 anti-materiel sniper rifle. Hyper-velocity piercing rounds with colossal critical damage!',
    stats: { atk: 140, speed: 2, crit: 45 },
    price: 2400,
  },

  // Melee & Boss Sledge
  'wpn_welder_sledge': {
    id: 'wpn_welder_sledge',
    name: 'Industrial Welder Sledgehammer',
    type: 'weapon',
    gunType: 'sledgehammer',
    rarity: 'legendary',
    icon: '🔨',
    description: 'Massive heavy hammer salvaged from "Iron Mask" Sledge. Smashes ground fissures with colossal blunt force.',
    stats: { atk: 110, def: 25, crit: 20, maxHp: 220 },
    price: 2800,
  },
  'wpn_neon_katana': {
    id: 'wpn_neon_katana',
    name: 'Machete / Trench Blade',
    type: 'weapon',
    gunType: 'katana',
    rarity: 'rare',
    icon: '🗡️',
    description: 'Tempered steel survival blade for high-speed melee sweeps.',
    stats: { atk: 32, speed: 8, crit: 15 },
    price: 320,
  },

  // Headwear & Survival Gear
  'head_welder_mask': {
    id: 'head_welder_mask',
    name: 'Heavy Welder Steel Visor',
    type: 'headwear',
    rarity: 'epic',
    icon: '🥽',
    description: 'Heavy plate welder helmet with narrow eye slit. Grants massive armor and blast resistance.',
    stats: { def: 28, maxHp: 160, atk: 12 },
    price: 650,
  },
  'head_outlaw_stetson': {
    id: 'head_outlaw_stetson',
    name: 'Outlaw Bandit Hat',
    type: 'headwear',
    rarity: 'rare',
    icon: '🤠',
    description: 'Weathered leather hat. Increases quick-draw agility and critical hit chance.',
    stats: { def: 14, crit: 12, speed: 5 },
    price: 320,
  },
  'head_cat_band': {
    id: 'head_cat_band',
    name: 'Survivor Headband',
    type: 'headwear',
    rarity: 'common',
    icon: '🎀',
    description: 'Comfortable cloth band that keeps sweat and dust out of your eyes.',
    stats: { def: 8, speed: 4, maxHp: 40 },
    price: 75,
  },

  // Outfits
  'outfit_leather_vest': {
    id: 'outfit_leather_vest',
    name: 'Reinforced Combat Trench',
    type: 'outfit',
    rarity: 'rare',
    icon: '🧥',
    description: 'Heavy tactical coat with kevlar lining and ammo bandoliers.',
    stats: { def: 24, maxHp: 140, speed: 3 },
    price: 450,
  },
  'outfit_cyber_hoodie': {
    id: 'outfit_cyber_hoodie',
    name: 'Survivor Field Parka',
    type: 'outfit',
    rarity: 'common',
    icon: '🥋',
    description: 'Insulated outdoor jacket for deep wilderness exploration.',
    stats: { def: 12, maxHp: 60 },
    price: 150,
  },

  // Vehicles
  'veh_skateboard': {
    id: 'veh_skateboard',
    name: 'Off-Road Timber Skateboard',
    type: 'vehicle',
    rarity: 'common',
    icon: '🛹',
    description: 'Cruiser board with rugged all-terrain wheels.',
    vehicleSpeed: 25,
    vehicleType: 'skateboard',
    price: 100,
  },
  'veh_hoverboard': {
    id: 'veh_hoverboard',
    name: 'Mag-Lev Desert Hoverboard',
    type: 'vehicle',
    rarity: 'rare',
    icon: '🛸',
    description: 'Glides seamlessly across rocks, mud, and water puddles.',
    vehicleSpeed: 45,
    vehicleType: 'hoverboard',
    price: 600,
  },

  // Consumables
  'item_hp_potion_s': {
    id: 'item_hp_potion_s',
    name: 'Military Field Medkit',
    type: 'consumable',
    rarity: 'common',
    icon: '🩹',
    description: 'Emergency gauze and adrenaline. Instantly restores 180 HP.',
    healHp: 180,
    price: 25,
    stackable: true,
  },
  'item_hp_potion_l': {
    id: 'item_hp_potion_l',
    name: 'Surgeon Trauma Kit',
    type: 'consumable',
    rarity: 'rare',
    icon: '💉',
    description: 'Advanced medical kit. Restores 500 HP.',
    healHp: 500,
    price: 75,
    stackable: true,
  },
  'item_ramen_bowl': {
    id: 'item_ramen_bowl',
    name: 'Campfire Stew & Rations',
    type: 'consumable',
    rarity: 'rare',
    icon: '🍲',
    description: 'Hearty campfire stew. Grants +30% Attack Power for 5 minutes.',
    buffDuration: 300,
    buffType: 'atk',
    buffValue: 30,
    healHp: 250,
    price: 90,
    stackable: true,
  },

  // Materials & Gatherables
  'mat_wood': {
    id: 'mat_wood',
    name: 'Pine Timber Log',
    type: 'material',
    rarity: 'common',
    icon: '🪵',
    description: 'Dense fragrant pine timber chopped in the forest.',
    price: 5,
    stackable: true,
  },
  'mat_iron_ore': {
    id: 'mat_iron_ore',
    name: 'Raw Iron Ore',
    type: 'material',
    rarity: 'common',
    icon: '🪨',
    description: 'Heavy raw iron mined from rocky canyon crags.',
    price: 8,
    stackable: true,
  },
  'mat_lumite_crystal': {
    id: 'mat_lumite_crystal',
    name: 'Luminescent Crystal',
    type: 'material',
    rarity: 'rare',
    icon: '💎',
    description: 'Glowing crystal discovered in deep forest hollows.',
    price: 25,
    stackable: true,
  },
  'mat_outlaw_badge': {
    id: 'mat_outlaw_badge',
    name: 'Bandit Dogtag / Badge',
    type: 'material',
    rarity: 'rare',
    icon: '⭐',
    description: 'Engraved skull insignia collected from defeated bandits.',
    price: 30,
    stackable: true,
  },
  'mat_welder_scrap': {
    id: 'mat_welder_scrap',
    name: 'Forged Titanium Ingot',
    type: 'material',
    rarity: 'epic',
    icon: '⚙️',
    description: 'Super-hardened alloy forged by "Iron Mask" Sledge.',
    price: 150,
    stackable: true,
  },
};

export const CRAFT_RECIPES: CraftRecipe[] = [
  {
    id: 'recipe_ak47',
    name: 'AK-47 Kalashnikov',
    category: 'weapons',
    resultItemId: 'wpn_ak47',
    resultQuantity: 1,
    unlockLevel: 3,
    materials: [
      { itemId: 'mat_iron_ore', count: 10 },
      { itemId: 'mat_wood', count: 6 },
      { itemId: 'mat_outlaw_badge', count: 4 },
    ],
  },
  {
    id: 'recipe_shotgun',
    name: 'Trench Sweeper Shotgun',
    category: 'weapons',
    resultItemId: 'wpn_shotgun',
    resultQuantity: 1,
    unlockLevel: 2,
    materials: [
      { itemId: 'mat_iron_ore', count: 8 },
      { itemId: 'mat_wood', count: 5 },
    ],
  },
  {
    id: 'recipe_cheytac',
    name: 'CheyTac M200 Intervention',
    category: 'weapons',
    resultItemId: 'wpn_cheytac',
    resultQuantity: 1,
    unlockLevel: 5,
    materials: [
      { itemId: 'mat_welder_scrap', count: 3 },
      { itemId: 'mat_iron_ore', count: 15 },
      { itemId: 'mat_lumite_crystal', count: 8 },
    ],
  },
  {
    id: 'recipe_medkit',
    name: 'Surgeon Trauma Kit',
    category: 'potions',
    resultItemId: 'item_hp_potion_l',
    resultQuantity: 2,
    unlockLevel: 1,
    materials: [
      { itemId: 'mat_lumite_crystal', count: 2 },
      { itemId: 'item_hp_potion_s', count: 2 },
    ],
  },
];

export const INITIAL_RESOURCE_NODES: ResourceNode[] = [
  // Camp & Forest Trees
  { id: 'node_tree_1', type: 'tree', name: 'Dense Pine Tree', x: 380, y: 320, hp: 30, maxHp: 30, dropItemId: 'mat_wood' },
  { id: 'node_tree_2', type: 'tree', name: 'Dense Pine Tree', x: 1050, y: 350, hp: 30, maxHp: 30, dropItemId: 'mat_wood' },
  { id: 'node_tree_3', type: 'tree', name: 'Dense Pine Tree', x: 1420, y: 550, hp: 30, maxHp: 30, dropItemId: 'mat_wood' },
  { id: 'node_tree_4', type: 'tree', name: 'Ancient Pine', x: 500, y: 1800, hp: 35, maxHp: 35, dropItemId: 'mat_wood' },
  { id: 'node_tree_5', type: 'tree', name: 'Ancient Pine', x: 950, y: 2200, hp: 35, maxHp: 35, dropItemId: 'mat_wood' },

  // Canyon & Crag Iron Ore Deposits
  { id: 'node_ore_1', type: 'iron_ore', name: 'Canyon Iron Vein', x: 2150, y: 350, hp: 45, maxHp: 45, dropItemId: 'mat_iron_ore' },
  { id: 'node_ore_2', type: 'iron_ore', name: 'Crag Iron Vein', x: 2900, y: 450, hp: 45, maxHp: 45, dropItemId: 'mat_iron_ore' },
  { id: 'node_ore_3', type: 'iron_ore', name: 'High Peak Iron Vein', x: 3650, y: 550, hp: 45, maxHp: 45, dropItemId: 'mat_iron_ore' },

  // Deep Woods Lumite Crystal Clusters
  { id: 'node_lumite_1', type: 'lumite_crystal', name: 'Lumite Glow Cluster', x: 750, y: 2550, hp: 50, maxHp: 50, dropItemId: 'mat_lumite_crystal' },
  { id: 'node_lumite_2', type: 'lumite_crystal', name: 'Lumite Glow Cluster', x: 1350, y: 2700, hp: 50, maxHp: 50, dropItemId: 'mat_lumite_crystal' },
];

export const NPCS_DATABASE: Record<string, NPC> = {
  'npc_hank_guide': {
    id: 'npc_hank_guide',
    name: 'Doc "Hank" Vance',
    title: 'Camp Commander & Medic',
    avatarChibi: {
      hairStyle: 'short_messy',
      hairColor: '#374151',
      earType: 'none',
      earColor: '#1F2937',
      haloType: 'none',
      haloColor: '#E2E8F0',
      coatColor: '#1E293B',
      skirtColor: '#334155',
      eyeType: 'determined',
      ribbonColor: '#DC2626',
    },
    role: 'quest',
    x: 650,
    y: 520, // Standing outside the main HQ tent
    dialogue: {
      greeting: "Glad you made it back to camp in one piece, kid. The outlaws are crawling all over the eastern canyon pass. If you're heading out, keep your finger on the trigger!",
      options: [
        { text: 'View Outpost Quests', action: 'open_quests' },
        { text: 'Treat my wounds (Heal)', action: 'heal', dialogueText: 'Here, have some sterile gauze and adrenaline. You are back at full combat strength!' },
        { text: 'Tell me about the Welder Boss', action: 'talk', dialogueText: 'Up at the high rocky crag lives "Iron Mask" Sledge. Big guy in a welding visor wielding a colossal hammer. Watch out when he slams the ground or calls his grunts!' },
      ],
    },
    questIds: ['quest_camp_security', 'quest_canyon_purge', 'quest_welder_bounty'],
  },

  'npc_seraph_smith': {
    id: 'npc_seraph_smith',
    name: 'Sarge Steel',
    title: 'Weaponsmith & Armorer',
    avatarChibi: {
      hairStyle: 'spiky',
      hairColor: '#D97706',
      earType: 'none',
      earColor: '#78350F',
      haloType: 'none',
      haloColor: '#F59E0B',
      coatColor: '#451A03',
      skirtColor: '#78350F',
      eyeType: 'smug',
      ribbonColor: '#F59E0B',
    },
    role: 'craft',
    x: 880,
    y: 540, // Next to the armory tent & anvil
    dialogue: {
      greeting: "Need some real firepower? Bring me raw iron ore, pine timber, and bandit dogtags, and I'll assemble Kalashnikovs, shotguns, and precision CheyTac snipers.",
      options: [
        { text: 'Open Weapon Workshop', action: 'open_craft' },
        { text: 'Browse Arsenal Shop', action: 'open_shop' },
      ],
    },
    craftRecipeIds: ['recipe_ak47', 'recipe_shotgun', 'recipe_cheytac', 'recipe_medkit'],
    shopItemIds: ['wpn_pistol', 'wpn_revolver', 'wpn_mac10', 'wpn_ak47', 'wpn_shotgun', 'item_hp_potion_s', 'item_hp_potion_l'],
  },

  'npc_momoi_guide': {
    id: 'npc_momoi_guide',
    name: 'Arona & Momoi',
    title: 'Camp Scout & Recon',
    avatarChibi: {
      hairStyle: 'twintails',
      hairColor: '#F472B6',
      earType: 'cat',
      earColor: '#BE185D',
      haloType: 'circle',
      haloColor: '#FB7185',
      coatColor: '#1E293B',
      skirtColor: '#475569',
      eyeType: 'happy',
      ribbonColor: '#F43F5E',
    },
    role: 'guide',
    x: 640,
    y: 720, // Sitting by the glowing campfire log
    dialogue: {
      greeting: "Warm up by the fire! Tip: Holding Space chains fast bunny hops to dodge enemy bullets! Defeated enemies also drop their weapons directly on the ground so you can swap your loadout anytime.",
      options: [
        { text: 'How do guns & weapons work?', action: 'talk', dialogueText: 'You can carry all 6 weapons (Pistol, Revolver, MAC-10, AK-47, Shotgun, CheyTac). Press [1]-[6] or click the weapon dock to switch instantly! Shoot red explosive barrels to wipe out crowds.' },
        { text: 'How do bunny hops work?', action: 'talk', dialogueText: 'Just hold [Space] while moving! You will continuously bounce forward and build up massive speed stacks.' },
      ],
    },
  },

  'npc_chibi_cafe': {
    id: 'npc_chibi_cafe',
    name: 'Luna',
    title: 'Camp Cook & Supplies',
    avatarChibi: {
      hairStyle: 'braids',
      hairColor: '#FB7185',
      earType: 'bunny',
      earColor: '#9F1239',
      haloType: 'none',
      haloColor: '#F43F5E',
      coatColor: '#FFF1F2',
      skirtColor: '#881337',
      eyeType: 'wink',
      ribbonColor: '#E11D48',
    },
    role: 'cafe',
    x: 440,
    y: 770, // In the kitchen tent
    dialogue: {
      greeting: "Hey survivor! Got hot campfire stew ready to give you +30% attack strength, along with field medkits and off-road boards!",
      options: [
        { text: 'Buy Rations & Gear', action: 'open_shop' },
      ],
    },
    shopItemIds: ['item_ramen_bowl', 'item_hp_potion_s', 'item_hp_potion_l', 'veh_skateboard', 'veh_hoverboard'],
  },
};

export const QUESTS_DATABASE: Record<string, Quest> = {
  'quest_camp_security': {
    id: 'quest_camp_security',
    title: 'Campsite Perimeter Defense',
    giverNpcId: 'npc_hank_guide',
    description: 'Clear the aggressive wolves and bandit grunts probing the forest camp borders.',
    minLevel: 1,
    objectives: [
      { type: 'kill', targetId: 'forest_wolf', targetName: 'Feral Wolves', current: 0, required: 3 },
      { type: 'kill', targetId: 'bandit_grunt', targetName: 'Bandit Grunts', current: 0, required: 3 },
    ],
    rewardExp: 200,
    rewardGold: 180,
    rewardItems: [
      { itemId: 'wpn_pistol', quantity: 1 },
      { itemId: 'item_hp_potion_s', quantity: 3 },
    ],
  },
  'quest_canyon_purge': {
    id: 'quest_canyon_purge',
    title: 'Canyon Pass Raid',
    giverNpcId: 'npc_hank_guide',
    description: 'Advance into the rocky canyon pass, eliminate outlaw gunslingers, and take down Viktor.',
    minLevel: 2,
    objectives: [
      { type: 'kill', targetId: 'bandit_scout', targetName: 'Outlaw Pistoleros', current: 0, required: 3 },
      { type: 'kill', targetId: 'boss_outlaw_viktor', targetName: 'Dead-Eye Viktor', current: 0, required: 1 },
    ],
    rewardExp: 600,
    rewardGold: 600,
    rewardItems: [
      { itemId: 'wpn_ak47', quantity: 1 },
      { itemId: 'item_hp_potion_l', quantity: 2 },
    ],
  },
  'quest_welder_bounty': {
    id: 'quest_welder_bounty',
    title: 'Bounty: "Iron Mask" Sledge',
    giverNpcId: 'npc_hank_guide',
    description: 'Ascend to the high mountain summit and vanquish the brutal hammer boss "Iron Mask" Sledge!',
    minLevel: 4,
    objectives: [
      { type: 'kill', targetId: 'boss_welder', targetName: '"Iron Mask" Sledge (Boss)', current: 0, required: 1 },
    ],
    rewardExp: 1500,
    rewardGold: 2000,
    rewardItems: [
      { itemId: 'wpn_cheytac', quantity: 1 },
      { itemId: 'head_welder_mask', quantity: 1 },
    ],
  },
};

export const INITIAL_MONSTERS: Monster[] = [
  // Forest Feral Wolves
  {
    id: 'mob_wolf_1',
    name: 'Shadowfang Wolf',
    type: 'forest_wolf',
    zone: 'deep_forest',
    x: 650,
    y: 1900,
    spawnX: 650,
    spawnY: 1900,
    maxHp: 90,
    hp: 90,
    atk: 14,
    def: 4,
    speed: 2.3,
    expReward: 45,
    goldReward: 30,
    state: 'idle',
    targetPlayerId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'item_hp_potion_s', chance: 0.6, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'mob_wolf_2',
    name: 'Shadowfang Wolf',
    type: 'forest_wolf',
    zone: 'deep_forest',
    x: 1200,
    y: 2300,
    spawnX: 1200,
    spawnY: 2300,
    maxHp: 90,
    hp: 90,
    atk: 14,
    def: 4,
    speed: 2.3,
    expReward: 45,
    goldReward: 30,
    state: 'idle',
    targetPlayerId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'item_hp_potion_s', chance: 0.6, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },

  // Sparring / Practice Cadets at Camp Outskirts
  {
    id: 'target_human_1',
    name: 'Sparring Partner (Brawler)',
    type: 'cadet_bat',
    zone: 'forest_camp',
    x: 1350,
    y: 650,
    spawnX: 1350,
    spawnY: 650,
    maxHp: 180,
    hp: 180,
    atk: 10,
    def: 4,
    speed: 1.9,
    expReward: 35,
    goldReward: 25,
    isHumanoid: true,
    weaponType: 'bat',
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_pistol', chance: 0.4, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_s', chance: 0.8, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },

  // CANYON & FOOTHILLS BANDIT OUTLAWS (Madness Combat Style Gunfighters)
  {
    id: 'bandit_grunt_1',
    name: 'Bandit Grunt (Club & Cleaver)',
    type: 'bandit_grunt',
    zone: 'rocky_canyon',
    x: 2150,
    y: 750,
    spawnX: 2150,
    spawnY: 750,
    maxHp: 160,
    hp: 160,
    atk: 18,
    def: 6,
    speed: 2.4,
    expReward: 60,
    goldReward: 50,
    isHumanoid: true,
    weaponType: 'bat',
    humanChibi: {
      hairStyle: 'spiky',
      hairColor: '#DC2626',
      earType: 'none',
      earColor: '#7F1D1D',
      haloType: 'cross',
      haloColor: '#EF4444',
      coatColor: '#334155',
      skirtColor: '#1E293B',
      eyeType: 'determined',
      ribbonColor: '#DC2626',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_pistol', chance: 0.45, minQty: 1, maxQty: 1 },
      { itemId: 'mat_outlaw_badge', chance: 0.8, minQty: 1, maxQty: 2 },
      { itemId: 'item_hp_potion_s', chance: 0.6, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'bandit_grunt_2',
    name: 'Bandit Grunt (Club & Cleaver)',
    type: 'bandit_grunt',
    zone: 'rocky_canyon',
    x: 2450,
    y: 920,
    spawnX: 2450,
    spawnY: 920,
    maxHp: 160,
    hp: 160,
    atk: 18,
    def: 6,
    speed: 2.4,
    expReward: 60,
    goldReward: 50,
    isHumanoid: true,
    weaponType: 'bat',
    humanChibi: {
      hairStyle: 'short_messy',
      hairColor: '#B91C1C',
      earType: 'none',
      earColor: '#7F1D1D',
      haloType: 'none',
      haloColor: '#EF4444',
      coatColor: '#1E293B',
      skirtColor: '#0F172A',
      eyeType: 'determined',
      ribbonColor: '#DC2626',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_mac10', chance: 0.35, minQty: 1, maxQty: 1 },
      { itemId: 'mat_outlaw_badge', chance: 0.8, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'bandit_scout_1',
    name: 'Outlaw Pistolero (Revolver)',
    type: 'bandit_scout',
    zone: 'rocky_canyon',
    x: 2650,
    y: 650,
    spawnX: 2650,
    spawnY: 650,
    maxHp: 180,
    hp: 180,
    atk: 22,
    def: 6,
    speed: 2.1,
    expReward: 75,
    goldReward: 65,
    isHumanoid: true,
    weaponType: 'revolver',
    humanChibi: {
      hairStyle: 'wavy',
      hairColor: '#F97316',
      earType: 'none',
      earColor: '#7C2D12',
      haloType: 'cross',
      haloColor: '#EA580C',
      coatColor: '#451A03',
      skirtColor: '#78350F',
      eyeType: 'smug',
      ribbonColor: '#F97316',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_bandit_revolver', chance: 0.4, minQty: 1, maxQty: 1 },
      { itemId: 'mat_outlaw_badge', chance: 0.85, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'bandit_shotgunner_1',
    name: 'Trench Shotgunner (Heavy)',
    type: 'bandit_shotgunner',
    zone: 'rocky_canyon',
    x: 3200,
    y: 880,
    spawnX: 3200,
    spawnY: 880,
    maxHp: 280,
    hp: 280,
    atk: 28,
    def: 12,
    speed: 1.8,
    expReward: 120,
    goldReward: 110,
    isHumanoid: true,
    weaponType: 'shotgun',
    humanChibi: {
      hairStyle: 'long_flowing',
      hairColor: '#4B5563',
      earType: 'none',
      earColor: '#1F2937',
      haloType: 'cyber_hex',
      haloColor: '#E11D48',
      coatColor: '#18181B',
      skirtColor: '#27272A',
      eyeType: 'determined',
      ribbonColor: '#E11D48',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_shotgun', chance: 0.45, minQty: 1, maxQty: 1 },
      { itemId: 'mat_outlaw_badge', chance: 0.9, minQty: 2, maxQty: 3 },
      { itemId: 'item_hp_potion_s', chance: 0.8, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'bandit_sniper_1',
    name: 'Outlaw Sniper (CheyTac)',
    type: 'bandit_sniper',
    zone: 'rocky_canyon',
    x: 3750,
    y: 520,
    spawnX: 3750,
    spawnY: 520,
    maxHp: 200,
    hp: 200,
    atk: 36,
    def: 8,
    speed: 1.7,
    expReward: 140,
    goldReward: 130,
    isHumanoid: true,
    weaponType: 'cheytac',
    humanChibi: {
      hairStyle: 'wolf_cut',
      hairColor: '#10B981',
      earType: 'none',
      earColor: '#065F46',
      haloType: 'star',
      haloColor: '#34D399',
      coatColor: '#064E3B',
      skirtColor: '#022C22',
      eyeType: 'determined',
      ribbonColor: '#10B981',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_cheytac', chance: 0.25, minQty: 1, maxQty: 1 },
      { itemId: 'wpn_ak47', chance: 0.35, minQty: 1, maxQty: 1 },
      { itemId: 'mat_outlaw_badge', chance: 1.0, minQty: 2, maxQty: 4 },
    ],
    animTimer: 0,
  },

  // MINIBOSS: "Dead-Eye" Viktor (Canyon Overlook)
  {
    id: 'boss_outlaw_viktor',
    name: 'Outlaw Warlord "Dead-Eye Viktor"',
    type: 'boss_outlaw_viktor',
    zone: 'rocky_canyon',
    x: 3950,
    y: 950,
    spawnX: 3950,
    spawnY: 950,
    maxHp: 1400,
    hp: 1400,
    atk: 42,
    def: 20,
    speed: 2.2,
    expReward: 700,
    goldReward: 800,
    isBoss: true,
    isHumanoid: true,
    weaponType: 'ak47',
    humanChibi: {
      hairStyle: 'spiky',
      hairColor: '#EF4444',
      earType: 'none',
      earColor: '#991B1B',
      haloType: 'cross',
      haloColor: '#DC2626',
      coatColor: '#0F172A',
      skirtColor: '#7F1D1D',
      eyeType: 'determined',
      ribbonColor: '#EF4444',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_ak47', chance: 0.75, minQty: 1, maxQty: 1 },
      { itemId: 'wpn_bandit_revolver', chance: 0.6, minQty: 1, maxQty: 1 },
      { itemId: 'head_outlaw_stetson', chance: 0.5, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_l', chance: 1.0, minQty: 2, maxQty: 3 },
      { itemId: 'mat_outlaw_badge', chance: 1.0, minQty: 5, maxQty: 8 },
    ],
    animTimer: 0,
  },

  // MAIN WORLD BOSS: "Iron Mask" Sledge (The Welder Boss with Giant Sledgehammer)
  {
    id: 'boss_welder',
    name: '"Iron Mask" Sledge (The Welder)',
    type: 'boss_welder',
    zone: 'welder_crag',
    x: 3650,
    y: 2350,
    spawnX: 3650,
    spawnY: 2350,
    maxHp: 2800,
    hp: 2800,
    atk: 58,
    def: 32,
    speed: 1.6,
    expReward: 1800,
    goldReward: 2500,
    isBoss: true,
    isHumanoid: true,
    weaponType: 'sledgehammer',
    humanChibi: {
      hairStyle: 'short_messy',
      hairColor: '#1F2937',
      earType: 'none',
      earColor: '#111827',
      haloType: 'crown',
      haloColor: '#F59E0B',
      coatColor: '#1C1917',
      skirtColor: '#44403C',
      eyeType: 'determined',
      ribbonColor: '#EA580C',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_welder_sledge', chance: 0.85, minQty: 1, maxQty: 1 },
      { itemId: 'head_welder_mask', chance: 0.75, minQty: 1, maxQty: 1 },
      { itemId: 'wpn_cheytac', chance: 0.5, minQty: 1, maxQty: 1 },
      { itemId: 'mat_welder_scrap', chance: 1.0, minQty: 4, maxQty: 6 },
      { itemId: 'item_ramen_bowl', chance: 1.0, minQty: 3, maxQty: 5 },
    ],
    animTimer: 0,
  },

  // =========================================================
  // FACTION 1: POLICE SWAT PRECINCT (LEFT WARZONE)
  // =========================================================
  {
    id: 'cop_patrol_1',
    name: 'Precinct Officer (Nightstick)',
    type: 'cop_officer',
    zone: 'cop_precinct',
    faction: 'police',
    x: 1800,
    y: 3450,
    spawnX: 1800,
    spawnY: 3450,
    maxHp: 240,
    hp: 240,
    atk: 22,
    def: 12,
    speed: 2.3,
    expReward: 90,
    goldReward: 80,
    isHumanoid: true,
    weaponType: 'baton',
    humanChibi: {
      hairStyle: 'short_messy',
      hairColor: '#0F172A',
      earType: 'none',
      earColor: '#0284C7',
      haloType: 'circle',
      haloColor: '#38BDF8',
      coatColor: '#1E3A8A',
      skirtColor: '#172554',
      eyeType: 'determined',
      ribbonColor: '#38BDF8',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_pistol', chance: 0.5, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_s', chance: 0.8, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'cop_patrol_2',
    name: 'Police Enforcer (9mm Pistol)',
    type: 'cop_officer',
    zone: 'cop_precinct',
    faction: 'police',
    x: 1950,
    y: 3600,
    spawnX: 1950,
    spawnY: 3600,
    maxHp: 220,
    hp: 220,
    atk: 24,
    def: 10,
    speed: 2.4,
    expReward: 95,
    goldReward: 85,
    isHumanoid: true,
    weaponType: 'pistol',
    humanChibi: {
      hairStyle: 'bob',
      hairColor: '#334155',
      earType: 'none',
      earColor: '#0284C7',
      haloType: 'cyber_hex',
      haloColor: '#0284C7',
      coatColor: '#1E40AF',
      skirtColor: '#0F172A',
      eyeType: 'determined',
      ribbonColor: '#60A5FA',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_pistol', chance: 0.6, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_s', chance: 0.7, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'cop_swat_1',
    name: 'SWAT Vanguard (Assault Shotgun)',
    type: 'cop_swat',
    zone: 'cop_precinct',
    faction: 'police',
    x: 2050,
    y: 3750,
    spawnX: 2050,
    spawnY: 3750,
    maxHp: 380,
    hp: 380,
    atk: 32,
    def: 18,
    speed: 2.0,
    expReward: 160,
    goldReward: 150,
    isHumanoid: true,
    weaponType: 'shotgun',
    humanChibi: {
      hairStyle: 'spiky',
      hairColor: '#1E293B',
      earType: 'none',
      earColor: '#0284C7',
      haloType: 'star',
      haloColor: '#38BDF8',
      coatColor: '#0F172A',
      skirtColor: '#09090B',
      eyeType: 'determined',
      ribbonColor: '#3B82F6',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_shotgun', chance: 0.45, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_l', chance: 0.6, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'cop_marksman_1',
    name: 'SWAT Overwatch (Sniper)',
    type: 'cop_marksman',
    zone: 'cop_precinct',
    faction: 'police',
    x: 1650,
    y: 3350,
    spawnX: 1650,
    spawnY: 3350,
    maxHp: 260,
    hp: 260,
    atk: 40,
    def: 12,
    speed: 1.9,
    expReward: 180,
    goldReward: 160,
    isHumanoid: true,
    weaponType: 'cheytac',
    humanChibi: {
      hairStyle: 'wolf_cut',
      hairColor: '#0284C7',
      earType: 'none',
      earColor: '#0369A1',
      haloType: 'star',
      haloColor: '#0EA5E9',
      coatColor: '#0F172A',
      skirtColor: '#1E3A8A',
      eyeType: 'determined',
      ribbonColor: '#38BDF8',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_cheytac', chance: 0.35, minQty: 1, maxQty: 1 },
    ],
    animTimer: 0,
  },

  // POLICE JUGGERNAUT: "Titan Bulwark"
  {
    id: 'cop_juggernaut_1',
    name: 'SWAT Juggernaut "Titan Bulwark"',
    type: 'cop_juggernaut',
    zone: 'cop_precinct',
    faction: 'police',
    isJuggernaut: true,
    isBoss: true,
    x: 1900,
    y: 3550,
    spawnX: 1900,
    spawnY: 3550,
    maxHp: 2400,
    hp: 2400,
    atk: 48,
    def: 35,
    speed: 1.5,
    expReward: 1400,
    goldReward: 1800,
    isHumanoid: true,
    weaponType: 'sledgehammer',
    humanChibi: {
      hairStyle: 'short_messy',
      hairColor: '#0284C7',
      earType: 'cyber_antennas',
      earColor: '#38BDF8',
      haloType: 'crown',
      haloColor: '#38BDF8',
      coatColor: '#0369A1',
      skirtColor: '#082F49',
      eyeType: 'determined',
      ribbonColor: '#0284C7',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_shotgun', chance: 0.8, minQty: 1, maxQty: 1 },
      { itemId: 'wpn_cheytac', chance: 0.5, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_l', chance: 1.0, minQty: 2, maxQty: 4 },
    ],
    animTimer: 0,
  },

  // =========================================================
  // FACTION 2: DEMON PUNK SYNDICATE (RIGHT WARZONE)
  // =========================================================
  {
    id: 'punk_anarchist_1',
    name: 'Punk Anarchist (Spiked Bat)',
    type: 'punk_grunt',
    zone: 'punk_territory',
    faction: 'punk_demon',
    x: 3200,
    y: 3450,
    spawnX: 3200,
    spawnY: 3450,
    maxHp: 250,
    hp: 250,
    atk: 25,
    def: 10,
    speed: 2.5,
    expReward: 95,
    goldReward: 85,
    isHumanoid: true,
    weaponType: 'bat',
    humanChibi: {
      hairStyle: 'spiky',
      hairColor: '#F43F5E',
      earType: 'horns',
      earColor: '#BE123C',
      haloType: 'cross',
      haloColor: '#E11D48',
      coatColor: '#18181B',
      skirtColor: '#881337',
      eyeType: 'determined',
      ribbonColor: '#F43F5E',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_mac10', chance: 0.4, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_s', chance: 0.8, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'punk_molotov_1',
    name: 'Hellfire Pyro (Molotov Cocktail)',
    type: 'punk_molotov',
    zone: 'punk_territory',
    faction: 'punk_demon',
    x: 3100,
    y: 3650,
    spawnX: 3100,
    spawnY: 3650,
    maxHp: 220,
    hp: 220,
    atk: 30,
    def: 8,
    speed: 2.2,
    expReward: 120,
    goldReward: 110,
    isHumanoid: true,
    weaponType: 'molotov',
    humanChibi: {
      hairStyle: 'cyber_buns',
      hairColor: '#FB923C',
      earType: 'horns',
      earColor: '#C2410C',
      haloType: 'floral',
      haloColor: '#EA580C',
      coatColor: '#27272A',
      skirtColor: '#7C2D12',
      eyeType: 'smug',
      ribbonColor: '#F97316',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_mac10', chance: 0.5, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_s', chance: 0.8, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },
  {
    id: 'punk_gunner_1',
    name: 'Demon Outlaw (MAC-10 SMG)',
    type: 'punk_anarchist',
    zone: 'punk_territory',
    faction: 'punk_demon',
    x: 3350,
    y: 3750,
    spawnX: 3350,
    spawnY: 3750,
    maxHp: 270,
    hp: 270,
    atk: 28,
    def: 12,
    speed: 2.4,
    expReward: 150,
    goldReward: 140,
    isHumanoid: true,
    weaponType: 'mac10',
    humanChibi: {
      hairStyle: 'wolf_cut',
      hairColor: '#A855F7',
      earType: 'horns',
      earColor: '#7E22CE',
      haloType: 'cross',
      haloColor: '#C084FC',
      coatColor: '#18181B',
      skirtColor: '#581C87',
      eyeType: 'determined',
      ribbonColor: '#A855F7',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_mac10', chance: 0.6, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_l', chance: 0.6, minQty: 1, maxQty: 2 },
    ],
    animTimer: 0,
  },

  // DEMON PUNK JUGGERNAUT: "Hellfire Jax"
  {
    id: 'punk_juggernaut_1',
    name: 'Demon Overlord "Hellfire Jax"',
    type: 'punk_juggernaut',
    zone: 'punk_territory',
    faction: 'punk_demon',
    isJuggernaut: true,
    isBoss: true,
    x: 3100,
    y: 3550,
    spawnX: 3100,
    spawnY: 3550,
    maxHp: 2600,
    hp: 2600,
    atk: 52,
    def: 30,
    speed: 1.6,
    expReward: 1500,
    goldReward: 2000,
    isHumanoid: true,
    weaponType: 'ak47',
    humanChibi: {
      hairStyle: 'spiky',
      hairColor: '#DC2626',
      earType: 'horns',
      earColor: '#991B1B',
      haloType: 'crown',
      haloColor: '#EF4444',
      coatColor: '#09090B',
      skirtColor: '#450A0A',
      eyeType: 'determined',
      ribbonColor: '#DC2626',
    },
    headTilt: 0,
    headTiltVel: 0,
    knockbackX: 0,
    knockbackY: 0,
    state: 'idle',
    targetPlayerId: null,
    targetMonsterId: null,
    attackCooldown: 0,
    specialCooldown: 0,
    dropTable: [
      { itemId: 'wpn_ak47', chance: 0.85, minQty: 1, maxQty: 1 },
      { itemId: 'wpn_bandit_revolver', chance: 0.7, minQty: 1, maxQty: 1 },
      { itemId: 'item_hp_potion_l', chance: 1.0, minQty: 2, maxQty: 4 },
    ],
    animTimer: 0,
  },
];

export const CLASS_DEFAULTS = {
  gunslinger: {
    name: 'Outlaw Gunslinger',
    desc: 'High-velocity firearm specialist with rapid bullet stream, fan spread, and aerial ricochet.',
    baseHp: 320,
    baseMp: 100,
    baseAtk: 24,
    baseDef: 14,
    baseSpd: 4.8,
    starterWeapon: 'wpn_starter_pistol',
    starterSkills: [
      {
        id: 'skill_gatling_burst',
        name: 'Rapid Fire Burst',
        icon: '⚡',
        description: 'Fires an automatic rapid-fire stream of 12 high-velocity bullets toward your cursor.',
        costMp: 0,
        cooldown: 2.2,
        lastUsed: 0,
        unlockLevel: 1,
        level: 1,
        maxLevel: 5,
        type: 'damage' as const,
        damageMult: 2.5,
        range: 1200,
      },
      {
        id: 'skill_bullet_fan',
        name: 'Fan of Bullets (Spread)',
        icon: '💥',
        description: 'Unleashes a wide 9-bullet penetrating spread in a 75-degree frontal cone.',
        costMp: 0,
        cooldown: 3.2,
        lastUsed: 0,
        unlockLevel: 2,
        level: 1,
        maxLevel: 5,
        type: 'aoe' as const,
        damageMult: 2.8,
        range: 1100,
      },
      {
        id: 'skill_aerial_aimbot',
        name: 'Aerial Aimbot & Ricochet',
        icon: '🎯',
        description: 'Vaults high into the air with aimbot laser locks, raining down homing bullets that ricochet between targets!',
        costMp: 0,
        cooldown: 7.0,
        lastUsed: 0,
        unlockLevel: 3,
        level: 1,
        maxLevel: 5,
        type: 'ultimate' as const,
        damageMult: 4.8,
        range: 1400,
      },
    ],
  },
  swordmaster: {
    name: 'Survival Blade Fighter',
    desc: 'Melee fighter executing crescent slashes, flash step teleport strikes, and blade storm.',
    baseHp: 400,
    baseMp: 80,
    baseAtk: 30,
    baseDef: 20,
    baseSpd: 4.5,
    starterWeapon: 'wpn_neon_katana',
    starterSkills: [
      {
        id: 'skill_crescent_slash',
        name: 'Whirlwind Blade Sweep',
        icon: '🗡️',
        description: 'Performs a sweeping 360-degree whirlwind slash knocking enemies back.',
        costMp: 0,
        cooldown: 2.0,
        lastUsed: 0,
        unlockLevel: 1,
        level: 1,
        maxLevel: 5,
        type: 'aoe' as const,
        damageMult: 2.6,
        range: 200,
      },
      {
        id: 'skill_flash_step',
        name: 'Flash Step Dash Strike',
        icon: '💨',
        description: 'Dashes forward with invulnerability frames, slashing all targets in your path.',
        costMp: 0,
        cooldown: 3.5,
        lastUsed: 0,
        unlockLevel: 2,
        level: 1,
        maxLevel: 5,
        type: 'dash' as const,
        damageMult: 3.0,
        range: 300,
      },
      {
        id: 'skill_blade_storm',
        name: 'Blade Storm & Falling Swords',
        icon: '⚔️',
        description: 'Calls down radiant blades from above, impaling all nearby enemies.',
        costMp: 0,
        cooldown: 7.0,
        lastUsed: 0,
        unlockLevel: 3,
        level: 1,
        maxLevel: 5,
        type: 'ultimate' as const,
        damageMult: 5.0,
        range: 400,
      },
    ],
  },
  cybermage: {
    name: 'Field Tactician',
    desc: 'Support caster with explosive energy orbs, gravity vortex, and orbital laser barrage.',
    baseHp: 290,
    baseMp: 140,
    baseAtk: 26,
    baseDef: 12,
    baseSpd: 4.6,
    starterWeapon: 'wpn_starter_pistol',
    starterSkills: [
      {
        id: 'skill_arcane_burst',
        name: 'Explosive Energy Orb',
        icon: '🔮',
        description: 'Launches a pulsing energy sphere that detonates on impact.',
        costMp: 0,
        cooldown: 2.0,
        lastUsed: 0,
        unlockLevel: 1,
        level: 1,
        maxLevel: 5,
        type: 'damage' as const,
        damageMult: 2.4,
        range: 1200,
      },
      {
        id: 'skill_gravity_well',
        name: 'Gravity Vortex Pull',
        icon: '🌀',
        description: 'Creates a gravitational anomaly that pulls enemies together.',
        costMp: 0,
        cooldown: 4.5,
        lastUsed: 0,
        unlockLevel: 2,
        level: 1,
        maxLevel: 5,
        type: 'aoe' as const,
        damageMult: 2.2,
        range: 600,
      },
      {
        id: 'skill_orbital_strike',
        name: 'Tactical Artillery Bombardment',
        icon: '☄️',
        description: 'Orders high-explosive artillery strikes at your cursor location.',
        costMp: 0,
        cooldown: 8.0,
        lastUsed: 0,
        unlockLevel: 3,
        level: 1,
        maxLevel: 5,
        type: 'ultimate' as const,
        damageMult: 5.5,
        range: 800,
      },
    ],
  },
};
